-- One-off data seed script -- NOT a numbered schema migration. Run manually
-- (e.g. `psql -f scripts/fix_trilha_java_class_structure.sql`) against a
-- database that already has scripts/seed_trilha_java.sql applied.
--
-- Replaces the "java" key in starter_code_by_language for all 41 trilha-*
-- challenges with a new harness convention. The old convention put the
-- teacher's harness main() directly inside the student's own Solution
-- class, appended after the marker -- which only worked because the
-- visible stub was left with its closing brace missing, relying on the
-- student never closing it. That's fragile and pedagogically backwards: it
-- fights a Java programmer's instinct to always close what they open, and
-- a student who "fixes" the missing brace (as any reasonable Java
-- programmer would) broke compilation with "class, interface, enum, or
-- record expected" / unnamed-classes errors, since main() ended up
-- floating outside any class.
--
-- New convention: the visible stub's `public class Solution { ... }` is
-- COMPLETE AND CLOSED, exactly as a student would naturally write it. The
-- hidden harness below the marker is now a separate, non-public `class
-- Runner` containing main() -- it reads stdin, calls Solution's methods
-- or nested classes (now qualified as Solution.xxx, since Runner is a
-- different class), and prints output. judge/internal/worker/executor.go
-- was updated to run `java Runner` when a Runner.class is produced by
-- javac, falling back to `java Solution` for any non-marker Java
-- submission (unaffected by this change).
--
-- Business logic (method/constructor bodies, i.e. what a correct
-- implementation looks like) is untouched -- only the class structure
-- changed. Every one of the 41 harnesses below was locally compiled
-- (javac) and run (java) with a throwaway correct reference
-- implementation inside eclipse-temurin:21-jdk-alpine, using the judge's
-- exact javac/java invocation, against each challenge's sample test case,
-- and confirmed byte-for-byte (after trim) before being included here --
-- both with the stub's class closed normally (the previously-broken
-- scenario) and with the stub used as-is. Idempotent: safe to re-run.
--
-- Generated by Claude Code.

BEGIN;

-- trilha-n1-soma-media
UPDATE challenges
SET starter_code_by_language = jsonb_set(
  COALESCE(starter_code_by_language, '{}'::jsonb),
  '{java}',
  to_jsonb($JAVA_1$import java.util.Scanner;

public class Solution {
    static int somar(int a, int b) {
        // TODO
        return 0;
    }

    static double media(int a, int b) {
        // TODO
        return 0;
    }
}
[[ASCEND::RUNNER]]
class Runner {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        int a = scanner.nextInt();
        int b = scanner.nextInt();
        System.out.println(Solution.somar(a, b));
        System.out.printf("%.1f%n", Solution.media(a, b));
    }
}$JAVA_1$::text)
)
WHERE slug = 'trilha-n1-soma-media';

-- trilha-n1-par-impar
UPDATE challenges
SET starter_code_by_language = jsonb_set(
  COALESCE(starter_code_by_language, '{}'::jsonb),
  '{java}',
  to_jsonb($JAVA_2$import java.util.Scanner;

public class Solution {
    static String descrever(int n) {
        // TODO
        return "";
    }
}
[[ASCEND::RUNNER]]
class Runner {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        int n = scanner.nextInt();
        System.out.println(Solution.descrever(n));
    }
}$JAVA_2$::text)
)
WHERE slug = 'trilha-n1-par-impar';

-- trilha-n1-inverte-caixa
UPDATE challenges
SET starter_code_by_language = jsonb_set(
  COALESCE(starter_code_by_language, '{}'::jsonb),
  '{java}',
  to_jsonb($JAVA_3$import java.util.Scanner;

public class Solution {
    static String inverter_caixa(String texto) {
        // TODO
        return "";
    }
}
[[ASCEND::RUNNER]]
class Runner {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        String texto = scanner.nextLine();
        System.out.println(Solution.inverter_caixa(texto));
    }
}$JAVA_3$::text)
)
WHERE slug = 'trilha-n1-inverte-caixa';

-- trilha-n1-area-circulo
UPDATE challenges
SET starter_code_by_language = jsonb_set(
  COALESCE(starter_code_by_language, '{}'::jsonb),
  '{java}',
  to_jsonb($JAVA_4$import java.util.Scanner;

public class Solution {
    static double area_circulo(double r) {
        // TODO
        return 0;
    }
}
[[ASCEND::RUNNER]]
class Runner {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        double r = scanner.nextDouble();
        System.out.printf("%.2f%n", Solution.area_circulo(r));
    }
}$JAVA_4$::text)
)
WHERE slug = 'trilha-n1-area-circulo';

-- trilha-n1-conversor-segundos
UPDATE challenges
SET starter_code_by_language = jsonb_set(
  COALESCE(starter_code_by_language, '{}'::jsonb),
  '{java}',
  to_jsonb($JAVA_5$import java.util.Scanner;

public class Solution {
    static String converter(int total_segundos) {
        // TODO
        return "";
    }
}
[[ASCEND::RUNNER]]
class Runner {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        int total = scanner.nextInt();
        System.out.println(Solution.converter(total));
    }
}$JAVA_5$::text)
)
WHERE slug = 'trilha-n1-conversor-segundos';

-- trilha-n1-maioridade
UPDATE challenges
SET starter_code_by_language = jsonb_set(
  COALESCE(starter_code_by_language, '{}'::jsonb),
  '{java}',
  to_jsonb($JAVA_6$import java.util.Scanner;

public class Solution {
    static String classificar(int idade) {
        // TODO
        return "";
    }
}
[[ASCEND::RUNNER]]
class Runner {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        int idade = scanner.nextInt();
        System.out.println(Solution.classificar(idade));
    }
}$JAVA_6$::text)
)
WHERE slug = 'trilha-n1-maioridade';

-- trilha-n1-saudacao-turno
UPDATE challenges
SET starter_code_by_language = jsonb_set(
  COALESCE(starter_code_by_language, '{}'::jsonb),
  '{java}',
  to_jsonb($JAVA_7$import java.util.Scanner;

public class Solution {
    static String saudacao(int hora) {
        // TODO
        return "";
    }
}
[[ASCEND::RUNNER]]
class Runner {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        int hora = scanner.nextInt();
        System.out.println(Solution.saudacao(hora));
    }
}$JAVA_7$::text)
)
WHERE slug = 'trilha-n1-saudacao-turno';

-- trilha-n2-conta-palavras
UPDATE challenges
SET starter_code_by_language = jsonb_set(
  COALESCE(starter_code_by_language, '{}'::jsonb),
  '{java}',
  to_jsonb($JAVA_8$import java.util.Scanner;

public class Solution {
    static int contar_palavras(String frase) {
        // TODO
        return 0;
    }
}
[[ASCEND::RUNNER]]
class Runner {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        String frase = scanner.nextLine();
        System.out.println(Solution.contar_palavras(frase));
    }
}$JAVA_8$::text)
)
WHERE slug = 'trilha-n2-conta-palavras';

-- trilha-n2-maior-sem-max
UPDATE challenges
SET starter_code_by_language = jsonb_set(
  COALESCE(starter_code_by_language, '{}'::jsonb),
  '{java}',
  to_jsonb($JAVA_9$import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;

public class Solution {
    static int maior(List<Integer> numeros) {
        // TODO
        return 0;
    }
}
[[ASCEND::RUNNER]]
class Runner {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        List<Integer> valores = new ArrayList<>();
        while (scanner.hasNextInt()) {
            valores.add(scanner.nextInt());
        }
        System.out.println(Solution.maior(valores));
    }
}$JAVA_9$::text)
)
WHERE slug = 'trilha-n2-maior-sem-max';

-- trilha-n2-espacos-duplicados
UPDATE challenges
SET starter_code_by_language = jsonb_set(
  COALESCE(starter_code_by_language, '{}'::jsonb),
  '{java}',
  to_jsonb($JAVA_10$import java.util.Scanner;

public class Solution {
    static String normalizar(String texto) {
        // TODO
        return "";
    }
}
[[ASCEND::RUNNER]]
class Runner {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        String texto = scanner.nextLine();
        System.out.println(Solution.normalizar(texto));
    }
}$JAVA_10$::text)
)
WHERE slug = 'trilha-n2-espacos-duplicados';

-- trilha-n2-soma-pares
UPDATE challenges
SET starter_code_by_language = jsonb_set(
  COALESCE(starter_code_by_language, '{}'::jsonb),
  '{java}',
  to_jsonb($JAVA_11$import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;

public class Solution {
    static int soma_pares(List<Integer> numeros) {
        // TODO
        return 0;
    }
}
[[ASCEND::RUNNER]]
class Runner {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        List<Integer> valores = new ArrayList<>();
        while (scanner.hasNextInt()) {
            valores.add(scanner.nextInt());
        }
        System.out.println(Solution.soma_pares(valores));
    }
}$JAVA_11$::text)
)
WHERE slug = 'trilha-n2-soma-pares';

-- trilha-n2-conta-letra
UPDATE challenges
SET starter_code_by_language = jsonb_set(
  COALESCE(starter_code_by_language, '{}'::jsonb),
  '{java}',
  to_jsonb($JAVA_12$import java.util.Scanner;

public class Solution {
    static int contar_letra(String frase, String letra) {
        // TODO
        return 0;
    }
}
[[ASCEND::RUNNER]]
class Runner {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        String frase = scanner.nextLine();
        String letra = scanner.nextLine();
        System.out.println(Solution.contar_letra(frase, letra));
    }
}$JAVA_12$::text)
)
WHERE slug = 'trilha-n2-conta-letra';

-- trilha-n2-inverte-palavras
UPDATE challenges
SET starter_code_by_language = jsonb_set(
  COALESCE(starter_code_by_language, '{}'::jsonb),
  '{java}',
  to_jsonb($JAVA_13$import java.util.Scanner;

public class Solution {
    static String inverter_palavras(String frase) {
        // TODO
        return "";
    }
}
[[ASCEND::RUNNER]]
class Runner {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        String frase = scanner.nextLine();
        System.out.println(Solution.inverter_palavras(frase));
    }
}$JAVA_13$::text)
)
WHERE slug = 'trilha-n2-inverte-palavras';

-- trilha-n2-media-sem-extremos
UPDATE challenges
SET starter_code_by_language = jsonb_set(
  COALESCE(starter_code_by_language, '{}'::jsonb),
  '{java}',
  to_jsonb($JAVA_14$import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;

public class Solution {
    static double media_sem_extremos(List<Integer> numeros) {
        // TODO
        return 0;
    }
}
[[ASCEND::RUNNER]]
class Runner {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        List<Integer> valores = new ArrayList<>();
        while (scanner.hasNextInt()) {
            valores.add(scanner.nextInt());
        }
        System.out.printf("%.2f%n", Solution.media_sem_extremos(valores));
    }
}$JAVA_14$::text)
)
WHERE slug = 'trilha-n2-media-sem-extremos';

-- trilha-n3-anagrama
UPDATE challenges
SET starter_code_by_language = jsonb_set(
  COALESCE(starter_code_by_language, '{}'::jsonb),
  '{java}',
  to_jsonb($JAVA_15$import java.util.Scanner;

public class Solution {
    static boolean eh_anagrama(String a, String b) {
        // TODO
        return false;
    }
}
[[ASCEND::RUNNER]]
class Runner {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        String a = scanner.nextLine();
        String b = scanner.nextLine();
        System.out.println(Solution.eh_anagrama(a, b) ? "sim" : "nao");
    }
}$JAVA_15$::text)
)
WHERE slug = 'trilha-n3-anagrama';

-- trilha-n3-mais-frequente
UPDATE challenges
SET starter_code_by_language = jsonb_set(
  COALESCE(starter_code_by_language, '{}'::jsonb),
  '{java}',
  to_jsonb($JAVA_16$import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;

public class Solution {
    static int mais_frequente(List<Integer> numeros) {
        // TODO
        return 0;
    }
}
[[ASCEND::RUNNER]]
class Runner {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        List<Integer> valores = new ArrayList<>();
        while (scanner.hasNextInt()) {
            valores.add(scanner.nextInt());
        }
        System.out.println(Solution.mais_frequente(valores));
    }
}$JAVA_16$::text)
)
WHERE slug = 'trilha-n3-mais-frequente';

-- trilha-n3-estatistica-lista
UPDATE challenges
SET starter_code_by_language = jsonb_set(
  COALESCE(starter_code_by_language, '{}'::jsonb),
  '{java}',
  to_jsonb($JAVA_17$import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;

public class Solution {
    static class Estatistica {
        List<Integer> numeros;

        Estatistica(List<Integer> numeros) {
            this.numeros = numeros;
        }

        double media() {
            // TODO
            return 0;
        }

        double mediana() {
            // TODO
            return 0;
        }

        int moda() {
            // TODO
            return 0;
        }
    }
}
[[ASCEND::RUNNER]]
class Runner {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        List<Integer> valores = new ArrayList<>();
        while (scanner.hasNextInt()) {
            valores.add(scanner.nextInt());
        }
        Solution.Estatistica e = new Solution.Estatistica(valores);
        System.out.printf("%.2f%n", e.media());
        System.out.printf("%.2f%n", e.mediana());
        System.out.println(e.moda());
    }
}$JAVA_17$::text)
)
WHERE slug = 'trilha-n3-estatistica-lista';

-- trilha-n3-conta-caracteres
UPDATE challenges
SET starter_code_by_language = jsonb_set(
  COALESCE(starter_code_by_language, '{}'::jsonb),
  '{java}',
  to_jsonb($JAVA_18$import java.util.Scanner;

public class Solution {
    static String contar_caracteres(String palavra) {
        // TODO
        return "";
    }
}
[[ASCEND::RUNNER]]
class Runner {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        String palavra = scanner.nextLine();
        System.out.println(Solution.contar_caracteres(palavra));
    }
}$JAVA_18$::text)
)
WHERE slug = 'trilha-n3-conta-caracteres';

-- trilha-n3-fusao-dicionarios
UPDATE challenges
SET starter_code_by_language = jsonb_set(
  COALESCE(starter_code_by_language, '{}'::jsonb),
  '{java}',
  to_jsonb($JAVA_19$import java.util.Map;
import java.util.Scanner;

public class Solution {
    static Map<String, Integer> fundir(Map<String, Integer> dict1, Map<String, Integer> dict2) {
        // TODO
        return null;
    }
}
[[ASCEND::RUNNER]]
class Runner {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        int n1 = scanner.nextInt();
        Map<String, Integer> d1 = new java.util.LinkedHashMap<>();
        for (int i = 0; i < n1; i++) {
            String k = scanner.next();
            int v = scanner.nextInt();
            d1.put(k, v);
        }
        int n2 = scanner.nextInt();
        Map<String, Integer> d2 = new java.util.LinkedHashMap<>();
        for (int i = 0; i < n2; i++) {
            String k = scanner.next();
            int v = scanner.nextInt();
            d2.put(k, v);
        }
        Map<String, Integer> resultado = Solution.fundir(d1, d2);
        Map<String, Integer> ordenado = new java.util.TreeMap<>(resultado);
        StringBuilder sb = new StringBuilder();
        boolean first = true;
        for (Map.Entry<String, Integer> e : ordenado.entrySet()) {
            if (!first) {
                sb.append(" ");
            }
            sb.append(e.getKey()).append(":").append(e.getValue());
            first = false;
        }
        System.out.println(sb.toString());
    }
}$JAVA_19$::text)
)
WHERE slug = 'trilha-n3-fusao-dicionarios';

-- trilha-n3-fila-fifo
UPDATE challenges
SET starter_code_by_language = jsonb_set(
  COALESCE(starter_code_by_language, '{}'::jsonb),
  '{java}',
  to_jsonb($JAVA_20$import java.util.LinkedList;
import java.util.Scanner;

public class Solution {
    static class FilaAtendimento {
        LinkedList<String> fila = new LinkedList<>();

        void chegar(String nome) {
            // TODO
        }

        void atender() {
            // TODO
        }
    }
}
[[ASCEND::RUNNER]]
class Runner {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        Solution.FilaAtendimento fila = new Solution.FilaAtendimento();
        while (scanner.hasNextLine()) {
            String linha = scanner.nextLine();
            if (linha.trim().isEmpty()) {
                continue;
            }
            String[] partes = linha.trim().split("\\s+");
            if (partes[0].equals("CHEGAR")) {
                fila.chegar(partes[1]);
            } else if (partes[0].equals("ATENDER")) {
                fila.atender();
            }
        }
    }
}$JAVA_20$::text)
)
WHERE slug = 'trilha-n3-fila-fifo';

-- trilha-n3-formato-cpf
UPDATE challenges
SET starter_code_by_language = jsonb_set(
  COALESCE(starter_code_by_language, '{}'::jsonb),
  '{java}',
  to_jsonb($JAVA_21$import java.util.Scanner;

public class Solution {
    static boolean formato_valido(String cpf) {
        // TODO
        return false;
    }
}
[[ASCEND::RUNNER]]
class Runner {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        String cpf = scanner.nextLine();
        System.out.println(Solution.formato_valido(cpf) ? "formato valido" : "formato invalido");
    }
}$JAVA_21$::text)
)
WHERE slug = 'trilha-n3-formato-cpf';

-- trilha-n4-linha-sudoku
UPDATE challenges
SET starter_code_by_language = jsonb_set(
  COALESCE(starter_code_by_language, '{}'::jsonb),
  '{java}',
  to_jsonb($JAVA_22$import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;

public class Solution {
    static boolean validar_linha(List<Integer> numeros) {
        // TODO
        return false;
    }
}
[[ASCEND::RUNNER]]
class Runner {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        String linha = scanner.nextLine();
        String[] campos = linha.trim().split("\\s+");
        List<Integer> numeros = new ArrayList<>();
        for (String c : campos) {
            numeros.add(Integer.parseInt(c));
        }
        System.out.println(Solution.validar_linha(numeros) ? "valido" : "invalido");
    }
}$JAVA_22$::text)
)
WHERE slug = 'trilha-n4-linha-sudoku';

-- trilha-n4-parenteses-multiplos
UPDATE challenges
SET starter_code_by_language = jsonb_set(
  COALESCE(starter_code_by_language, '{}'::jsonb),
  '{java}',
  to_jsonb($JAVA_23$import java.util.Scanner;

public class Solution {
    static boolean esta_balanceado(String texto) {
        // TODO
        return false;
    }
}
[[ASCEND::RUNNER]]
class Runner {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        String texto = scanner.nextLine();
        System.out.println(Solution.esta_balanceado(texto) ? "balanceado" : "desbalanceado");
    }
}$JAVA_23$::text)
)
WHERE slug = 'trilha-n4-parenteses-multiplos';

-- trilha-n4-rle
UPDATE challenges
SET starter_code_by_language = jsonb_set(
  COALESCE(starter_code_by_language, '{}'::jsonb),
  '{java}',
  to_jsonb($JAVA_24$import java.util.Scanner;

public class Solution {
    static String comprimir(String texto) {
        // TODO
        return "";
    }
}
[[ASCEND::RUNNER]]
class Runner {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        String texto = scanner.nextLine();
        System.out.println(Solution.comprimir(texto));
    }
}$JAVA_24$::text)
)
WHERE slug = 'trilha-n4-rle';

-- trilha-n4-carrinho-desconto
UPDATE challenges
SET starter_code_by_language = jsonb_set(
  COALESCE(starter_code_by_language, '{}'::jsonb),
  '{java}',
  to_jsonb($JAVA_25$import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;

public class Solution {
    static class Carrinho {
        List<Double> itens = new ArrayList<>();

        void adicionar(String produto, double preco) {
            // TODO
        }

        void total() {
            // TODO
        }
    }
}
[[ASCEND::RUNNER]]
class Runner {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        Solution.Carrinho carrinho = new Solution.Carrinho();
        while (scanner.hasNextLine()) {
            String linha = scanner.nextLine();
            if (linha.trim().isEmpty()) {
                continue;
            }
            String[] partes = linha.trim().split("\\s+");
            if (partes[0].equals("ADICIONAR")) {
                carrinho.adicionar(partes[1], Double.parseDouble(partes[2]));
            } else if (partes[0].equals("TOTAL")) {
                carrinho.total();
            }
        }
    }
}$JAVA_25$::text)
)
WHERE slug = 'trilha-n4-carrinho-desconto';

-- trilha-n4-grau-conexoes
UPDATE challenges
SET starter_code_by_language = jsonb_set(
  COALESCE(starter_code_by_language, '{}'::jsonb),
  '{java}',
  to_jsonb($JAVA_26$import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Scanner;
import java.util.Set;

public class Solution {
    static class RedeAmigos {
        Map<String, Set<String>> conexoes = new HashMap<>();

        void conectar(String a, String b) {
            // TODO
        }

        void grau(String pessoa) {
            // TODO
        }
    }
}
[[ASCEND::RUNNER]]
class Runner {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        Solution.RedeAmigos rede = new Solution.RedeAmigos();
        while (scanner.hasNextLine()) {
            String linha = scanner.nextLine();
            if (linha.trim().isEmpty()) {
                continue;
            }
            String[] partes = linha.trim().split("\\s+");
            if (partes[0].equals("CONECTAR")) {
                rede.conectar(partes[1], partes[2]);
            } else if (partes[0].equals("GRAU")) {
                rede.grau(partes[1]);
            }
        }
    }
}$JAVA_26$::text)
)
WHERE slug = 'trilha-n4-grau-conexoes';

-- trilha-n4-matriz-magica
UPDATE challenges
SET starter_code_by_language = jsonb_set(
  COALESCE(starter_code_by_language, '{}'::jsonb),
  '{java}',
  to_jsonb($JAVA_27$import java.util.Scanner;

public class Solution {
    static boolean eh_magica(int[][] matriz) {
        // TODO
        return false;
    }
}
[[ASCEND::RUNNER]]
class Runner {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        int n = scanner.nextInt();
        int[][] matriz = new int[n][n];
        for (int i = 0; i < n; i++) {
            for (int j = 0; j < n; j++) {
                matriz[i][j] = scanner.nextInt();
            }
        }
        System.out.println(Solution.eh_magica(matriz) ? "magica" : "nao magica");
    }
}$JAVA_27$::text)
)
WHERE slug = 'trilha-n4-matriz-magica';

-- trilha-n4-fila-impressao-prioridade
UPDATE challenges
SET starter_code_by_language = jsonb_set(
  COALESCE(starter_code_by_language, '{}'::jsonb),
  '{java}',
  to_jsonb($JAVA_28$import java.util.LinkedList;
import java.util.Scanner;

public class Solution {
    static class FilaImpressao {
        LinkedList<String> prioritarias = new LinkedList<>();
        LinkedList<String> normais = new LinkedList<>();

        void imprimir(String nome, String tipo) {
            // TODO
        }

        void proximo() {
            // TODO
        }
    }
}
[[ASCEND::RUNNER]]
class Runner {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        Solution.FilaImpressao fila = new Solution.FilaImpressao();
        while (scanner.hasNextLine()) {
            String linha = scanner.nextLine();
            if (linha.trim().isEmpty()) {
                continue;
            }
            String[] partes = linha.trim().split("\\s+");
            if (partes[0].equals("IMPRIMIR")) {
                fila.imprimir(partes[1], partes[2]);
            } else if (partes[0].equals("PROXIMO")) {
                fila.proximo();
            }
        }
    }
}$JAVA_28$::text)
)
WHERE slug = 'trilha-n4-fila-impressao-prioridade';

-- trilha-n5-estoque-validacao
UPDATE challenges
SET starter_code_by_language = jsonb_set(
  COALESCE(starter_code_by_language, '{}'::jsonb),
  '{java}',
  to_jsonb($JAVA_29$import java.util.HashMap;
import java.util.Map;
import java.util.Scanner;

public class Solution {
    static class Estoque {
        Map<String, Integer> produtos = new HashMap<>();

        void entrada(String produto, int quantidade) {
            // TODO
        }

        void saida(String produto, int quantidade) {
            // TODO
        }

        void consultar(String produto) {
            // TODO
        }
    }
}
[[ASCEND::RUNNER]]
class Runner {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        Solution.Estoque estoque = new Solution.Estoque();
        while (scanner.hasNextLine()) {
            String linha = scanner.nextLine();
            if (linha.trim().isEmpty()) {
                continue;
            }
            String[] partes = linha.trim().split("\\s+");
            if (partes[0].equals("ENTRADA")) {
                estoque.entrada(partes[1], Integer.parseInt(partes[2]));
            } else if (partes[0].equals("SAIDA")) {
                estoque.saida(partes[1], Integer.parseInt(partes[2]));
            } else if (partes[0].equals("CONSULTAR")) {
                estoque.consultar(partes[1]);
            }
        }
    }
}$JAVA_29$::text)
)
WHERE slug = 'trilha-n5-estoque-validacao';

-- trilha-n5-escola-aninhada
UPDATE challenges
SET starter_code_by_language = jsonb_set(
  COALESCE(starter_code_by_language, '{}'::jsonb),
  '{java}',
  to_jsonb($JAVA_30$import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.ArrayList;
import java.util.List;

public class Solution {
    static double media_aluno(List<Double> notas) {
        // TODO
        return 0;
    }

    static double media_turma(List<Double> mediasAlunos) {
        // TODO
        return 0;
    }
}
[[ASCEND::RUNNER]]
class Runner {
    public static void main(String[] args) throws IOException {
        BufferedReader reader = new BufferedReader(new InputStreamReader(System.in));
        int nTurmas = Integer.parseInt(reader.readLine().trim());
        for (int t = 0; t < nTurmas; t++) {
            String nomeTurma = reader.readLine();
            int nAlunos = Integer.parseInt(reader.readLine().trim());
            List<Double> medias = new ArrayList<>();
            for (int a = 0; a < nAlunos; a++) {
                String[] partes = reader.readLine().trim().split("\\s+");
                List<Double> notas = new ArrayList<>();
                for (int k = 1; k < partes.length; k++) {
                    notas.add(Double.parseDouble(partes[k]));
                }
                medias.add(Solution.media_aluno(notas));
            }
            System.out.printf("%s: %.2f%n", nomeTurma, Solution.media_turma(medias));
        }
    }
}$JAVA_30$::text)
)
WHERE slug = 'trilha-n5-escola-aninhada';

-- trilha-n5-cache-capacidade
UPDATE challenges
SET starter_code_by_language = jsonb_set(
  COALESCE(starter_code_by_language, '{}'::jsonb),
  '{java}',
  to_jsonb($JAVA_31$import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;

public class Solution {
    static class CacheSimples {
        int capacidade;
        List<String> itens = new ArrayList<>();

        CacheSimples(int capacidade) {
            this.capacidade = capacidade;
        }

        void adicionar(String item) {
            // TODO
        }

        void listar() {
            // TODO
        }
    }
}
[[ASCEND::RUNNER]]
class Runner {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        int capacidade = Integer.parseInt(scanner.nextLine().trim());
        Solution.CacheSimples cache = new Solution.CacheSimples(capacidade);
        while (scanner.hasNextLine()) {
            String linha = scanner.nextLine();
            if (linha.trim().isEmpty()) {
                continue;
            }
            String[] partes = linha.trim().split("\\s+");
            if (partes[0].equals("ADICIONAR")) {
                cache.adicionar(partes[1]);
            } else if (partes[0].equals("LISTAR")) {
                cache.listar();
            }
        }
    }
}$JAVA_31$::text)
)
WHERE slug = 'trilha-n5-cache-capacidade';

-- trilha-n5-classificador-times
UPDATE challenges
SET starter_code_by_language = jsonb_set(
  COALESCE(starter_code_by_language, '{}'::jsonb),
  '{java}',
  to_jsonb($JAVA_32$import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Scanner;

public class Solution {
    static class Campeonato {
        List<String> ordem;
        Map<String, Integer> pontos = new LinkedHashMap<>();

        Campeonato(List<String> times) {
            this.ordem = times;
            for (String t : times) {
                pontos.put(t, 0);
            }
        }

        void registrar_resultado(String timeA, String timeB, int golsA, int golsB) {
            // TODO
        }

        List<Map.Entry<String, Integer>> ranking() {
            // TODO
            return null;
        }
    }
}
[[ASCEND::RUNNER]]
class Runner {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        int nTimes = Integer.parseInt(scanner.nextLine().trim());
        List<String> times = new ArrayList<>();
        for (int i = 0; i < nTimes; i++) {
            times.add(scanner.nextLine());
        }
        Solution.Campeonato campeonato = new Solution.Campeonato(times);
        int nResultados = Integer.parseInt(scanner.nextLine().trim());
        for (int i = 0; i < nResultados; i++) {
            String[] partes = scanner.nextLine().trim().split("\\s+");
            campeonato.registrar_resultado(partes[0], partes[1], Integer.parseInt(partes[2]), Integer.parseInt(partes[3]));
        }
        for (Map.Entry<String, Integer> r : campeonato.ranking()) {
            System.out.println(r.getKey() + ":" + r.getValue());
        }
    }
}$JAVA_32$::text)
)
WHERE slug = 'trilha-n5-classificador-times';

-- trilha-n5-votacao-desempate
UPDATE challenges
SET starter_code_by_language = jsonb_set(
  COALESCE(starter_code_by_language, '{}'::jsonb),
  '{java}',
  to_jsonb($JAVA_33$import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Scanner;

public class Solution {
    static class Votacao {
        List<String> ordemInscricao;
        Map<String, Integer> votos = new LinkedHashMap<>();

        Votacao(List<String> candidatosEmOrdem) {
            this.ordemInscricao = candidatosEmOrdem;
            for (String c : candidatosEmOrdem) {
                votos.put(c, 0);
            }
        }

        void votar(String candidato) {
            // TODO
        }

        List<Map.Entry<String, Integer>> ranking() {
            // TODO
            return null;
        }
    }
}
[[ASCEND::RUNNER]]
class Runner {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        int nCandidatos = Integer.parseInt(scanner.nextLine().trim());
        List<String> candidatos = new ArrayList<>();
        for (int i = 0; i < nCandidatos; i++) {
            candidatos.add(scanner.nextLine());
        }
        Solution.Votacao votacao = new Solution.Votacao(candidatos);
        int nVotos = Integer.parseInt(scanner.nextLine().trim());
        for (int i = 0; i < nVotos; i++) {
            votacao.votar(scanner.nextLine());
        }
        for (Map.Entry<String, Integer> r : votacao.ranking()) {
            System.out.println(r.getKey() + ":" + r.getValue());
        }
    }
}$JAVA_33$::text)
)
WHERE slug = 'trilha-n5-votacao-desempate';

-- trilha-n5-calculadora-frete
UPDATE challenges
SET starter_code_by_language = jsonb_set(
  COALESCE(starter_code_by_language, '{}'::jsonb),
  '{java}',
  to_jsonb($JAVA_34$import java.util.Scanner;

public class Solution {
    static double calcular_frete(double peso, double distancia, String tipo) {
        // TODO
        return 0;
    }
}
[[ASCEND::RUNNER]]
class Runner {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        double peso = scanner.nextDouble();
        double distancia = scanner.nextDouble();
        scanner.nextLine();
        String tipo = scanner.nextLine();
        System.out.printf("%.2f%n", Solution.calcular_frete(peso, distancia, tipo));
    }
}$JAVA_34$::text)
)
WHERE slug = 'trilha-n5-calculadora-frete';

-- trilha-n5-fila-multiplos-caixas
UPDATE challenges
SET starter_code_by_language = jsonb_set(
  COALESCE(starter_code_by_language, '{}'::jsonb),
  '{java}',
  to_jsonb($JAVA_35$import java.util.LinkedList;
import java.util.Scanner;

public class Solution {
    static class FilaBancoCaixas {
        int nCaixas;
        LinkedList<String> espera = new LinkedList<>();
        int proximoCaixa = 1;

        FilaBancoCaixas(int nCaixas) {
            this.nCaixas = nCaixas;
        }

        void chegar(String nome) {
            // TODO
        }

        void processar() {
            // TODO
        }
    }
}
[[ASCEND::RUNNER]]
class Runner {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        int nCaixas = Integer.parseInt(scanner.nextLine().trim());
        Solution.FilaBancoCaixas fila = new Solution.FilaBancoCaixas(nCaixas);
        while (scanner.hasNextLine()) {
            String linha = scanner.nextLine();
            if (linha.trim().isEmpty()) {
                continue;
            }
            String[] partes = linha.trim().split("\\s+");
            if (partes[0].equals("CHEGAR")) {
                fila.chegar(partes[1]);
            } else if (partes[0].equals("PROCESSAR")) {
                fila.processar();
            }
        }
    }
}$JAVA_35$::text)
)
WHERE slug = 'trilha-n5-fila-multiplos-caixas';

-- trilha-n6-hash-funcao
UPDATE challenges
SET starter_code_by_language = jsonb_set(
  COALESCE(starter_code_by_language, '{}'::jsonb),
  '{java}',
  to_jsonb($JAVA_36$import java.util.Scanner;

public class Solution {
    static int hash_simples(String chave, int tamanho) {
        // TODO
        return 0;
    }
}
[[ASCEND::RUNNER]]
class Runner {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        String chave = scanner.nextLine();
        int tamanho = scanner.nextInt();
        System.out.println(Solution.hash_simples(chave, tamanho));
    }
}$JAVA_36$::text)
)
WHERE slug = 'trilha-n6-hash-funcao';

-- trilha-n6-hash-inserir-listar
UPDATE challenges
SET starter_code_by_language = jsonb_set(
  COALESCE(starter_code_by_language, '{}'::jsonb),
  '{java}',
  to_jsonb($JAVA_37$import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;

public class Solution {
    static class TabelaHash {
        int tamanho;
        List<List<String>> tabela;

        TabelaHash(int tamanho) {
            this.tamanho = tamanho;
            this.tabela = new ArrayList<>();
            for (int i = 0; i < tamanho; i++) {
                tabela.add(new ArrayList<>());
            }
        }

        int _hash(String chave) {
            int soma = 0;
            for (char c : chave.toCharArray()) {
                soma += (int) c;
            }
            return soma % tamanho;
        }

        void inserir(String chave, String valor) {
            // TODO
        }

        void listar() {
            // TODO
        }
    }
}
[[ASCEND::RUNNER]]
class Runner {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        int tamanho = Integer.parseInt(scanner.nextLine().trim());
        Solution.TabelaHash tabela = new Solution.TabelaHash(tamanho);
        while (scanner.hasNextLine()) {
            String linha = scanner.nextLine();
            if (linha.trim().isEmpty()) {
                continue;
            }
            String[] partes = linha.trim().split("\\s+");
            if (partes[0].equals("INSERIR")) {
                tabela.inserir(partes[1], partes[2]);
            } else if (partes[0].equals("LISTAR")) {
                tabela.listar();
            }
        }
    }
}$JAVA_37$::text)
)
WHERE slug = 'trilha-n6-hash-inserir-listar';

-- trilha-n6-tabela-hash
UPDATE challenges
SET starter_code_by_language = jsonb_set(
  COALESCE(starter_code_by_language, '{}'::jsonb),
  '{java}',
  to_jsonb($JAVA_38$import java.util.Scanner;

public class Solution {
    static class TabelaHash {
        // TODO: adicione os campos necessarios

        TabelaHash(int tamanho) {
            // TODO
        }

        void inserir(String chave, String valor) {
            // TODO
        }

        String buscar(String chave) {
            // TODO
            return null;
        }
    }
}
[[ASCEND::RUNNER]]
class Runner {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        int n = Integer.parseInt(scanner.nextLine().trim());
        Solution.TabelaHash tabela = new Solution.TabelaHash(n);
        while (scanner.hasNextLine()) {
            String linha = scanner.nextLine();
            if (linha.trim().isEmpty()) {
                continue;
            }
            String[] partes = linha.trim().split("\\s+");
            if (partes[0].equals("INSERIR")) {
                tabela.inserir(partes[1], partes[2]);
            } else if (partes[0].equals("BUSCAR")) {
                String resultado = tabela.buscar(partes[1]);
                System.out.println(resultado != null ? resultado : "nao encontrado");
            }
        }
    }
}$JAVA_38$::text)
)
WHERE slug = 'trilha-n6-tabela-hash';

-- trilha-n6-hash-remocao
UPDATE challenges
SET starter_code_by_language = jsonb_set(
  COALESCE(starter_code_by_language, '{}'::jsonb),
  '{java}',
  to_jsonb($JAVA_39$import java.util.Scanner;

public class Solution {
    static class TabelaHash {
        // TODO: adicione os campos necessarios

        TabelaHash(int tamanho) {
            // TODO
        }

        void inserir(String chave, String valor) {
            // TODO
        }

        void remover(String chave) {
            // TODO
        }

        String buscar(String chave) {
            // TODO
            return null;
        }
    }
}
[[ASCEND::RUNNER]]
class Runner {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        int n = Integer.parseInt(scanner.nextLine().trim());
        Solution.TabelaHash tabela = new Solution.TabelaHash(n);
        while (scanner.hasNextLine()) {
            String linha = scanner.nextLine();
            if (linha.trim().isEmpty()) {
                continue;
            }
            String[] partes = linha.trim().split("\\s+");
            if (partes[0].equals("INSERIR")) {
                tabela.inserir(partes[1], partes[2]);
            } else if (partes[0].equals("REMOVER")) {
                tabela.remover(partes[1]);
            } else if (partes[0].equals("BUSCAR")) {
                String resultado = tabela.buscar(partes[1]);
                System.out.println(resultado != null ? resultado : "nao encontrado");
            }
        }
    }
}$JAVA_39$::text)
)
WHERE slug = 'trilha-n6-hash-remocao';

-- trilha-n6-hash-atualizacao
UPDATE challenges
SET starter_code_by_language = jsonb_set(
  COALESCE(starter_code_by_language, '{}'::jsonb),
  '{java}',
  to_jsonb($JAVA_40$import java.util.Scanner;

public class Solution {
    static class TabelaHash {
        // TODO: adicione os campos necessarios

        TabelaHash(int tamanho) {
            // TODO
        }

        void inserir(String chave, String valor) {
            // TODO
        }

        String buscar(String chave) {
            // TODO
            return null;
        }
    }
}
[[ASCEND::RUNNER]]
class Runner {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        int n = Integer.parseInt(scanner.nextLine().trim());
        Solution.TabelaHash tabela = new Solution.TabelaHash(n);
        while (scanner.hasNextLine()) {
            String linha = scanner.nextLine();
            if (linha.trim().isEmpty()) {
                continue;
            }
            String[] partes = linha.trim().split("\\s+");
            if (partes[0].equals("INSERIR")) {
                tabela.inserir(partes[1], partes[2]);
            } else if (partes[0].equals("BUSCAR")) {
                String resultado = tabela.buscar(partes[1]);
                System.out.println(resultado != null ? resultado : "nao encontrado");
            }
        }
    }
}$JAVA_40$::text)
)
WHERE slug = 'trilha-n6-hash-atualizacao';

-- trilha-n6-hash-rehashing
UPDATE challenges
SET starter_code_by_language = jsonb_set(
  COALESCE(starter_code_by_language, '{}'::jsonb),
  '{java}',
  to_jsonb($JAVA_41$import java.util.Scanner;

public class Solution {
    static class TabelaHash {
        int tamanho;
        // TODO: adicione os demais campos necessarios

        TabelaHash(int tamanho) {
            // TODO
        }

        void inserir(String chave, String valor) {
            // TODO
        }

        String buscar(String chave) {
            // TODO
            return null;
        }
    }
}
[[ASCEND::RUNNER]]
class Runner {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        int n = Integer.parseInt(scanner.nextLine().trim());
        Solution.TabelaHash tabela = new Solution.TabelaHash(n);
        while (scanner.hasNextLine()) {
            String linha = scanner.nextLine();
            if (linha.trim().isEmpty()) {
                continue;
            }
            String[] partes = linha.trim().split("\\s+");
            if (partes[0].equals("INSERIR")) {
                tabela.inserir(partes[1], partes[2]);
            } else if (partes[0].equals("TAMANHO")) {
                System.out.println(tabela.tamanho);
            } else if (partes[0].equals("BUSCAR")) {
                String resultado = tabela.buscar(partes[1]);
                System.out.println(resultado != null ? resultado : "nao encontrado");
            }
        }
    }
}$JAVA_41$::text)
)
WHERE slug = 'trilha-n6-hash-rehashing';

COMMIT;
