-- One-off data seed script -- NOT a numbered schema migration. Run manually
-- (e.g. `psql -f scripts/seed_trilha_multilang.sql`) against a database that
-- already has migration 000023 (starter_code_by_language column) applied.
-- Idempotent: safe to re-run, every statement is a plain UPDATE keyed by
-- slug.
--
-- Populates starter_code_by_language (python/javascript/go) for the 41
-- "Trilha de Evolucao" (trilha-*) challenges, then clears their pinned
-- language=python so the frontend language picker shows all three.
--
-- Generated by Claude Code; every JS/Go harness below was executed
-- (node / go run) against the challenge's sample test case and confirmed
-- byte-for-byte (after trim) before being included here. See the chat
-- transcript / final report for the two challenges with assumed business
-- rules (trilha-n4-carrinho-desconto discount %, trilha-n5-calculadora-frete
-- pricing formula) that could not be reverse-engineered from a single
-- sample case -- those only affect the throwaway test reference impls,
-- not the shipped stubs, which carry no business logic.

BEGIN;

-- trilha-n1-soma-media
UPDATE challenges
SET starter_code_by_language = jsonb_build_object(
  'python', $PY_1$def somar(a: int, b: int) -> int:
    pass

def media(a: int, b: int) -> float:
    pass

[[ASCEND::RUNNER]]
a = int(input())
b = int(input())
print(somar(a, b))
print(f"{media(a, b):.1f}")
$PY_1$,
  'javascript', $JS_1$function somar(a, b) {
  // TODO
}

function media(a, b) {
  // TODO
}
[[ASCEND::RUNNER]]
const __linhas = require('fs').readFileSync(0, 'utf8').split('\n');
const a = parseInt(__linhas[0], 10);
const b = parseInt(__linhas[1], 10);
console.log(somar(a, b));
console.log(media(a, b).toFixed(1));$JS_1$,
  'go', $GO_1$package main

import (
	"bufio"
	"fmt"
	"os"
)

func somar(a, b int) int {
	// TODO
	return 0
}

func media(a, b int) float64 {
	// TODO
	return 0
}
[[ASCEND::RUNNER]]
func main() {
	reader := bufio.NewReader(os.Stdin)
	var a, b int
	fmt.Fscan(reader, &a)
	fmt.Fscan(reader, &b)
	fmt.Println(somar(a, b))
	fmt.Printf("%.1f\n", media(a, b))
}$GO_1$
)
WHERE slug = 'trilha-n1-soma-media';

-- trilha-n1-par-impar
UPDATE challenges
SET starter_code_by_language = jsonb_build_object(
  'python', $PY_2$def descrever(n: int) -> str:
    pass

[[ASCEND::RUNNER]]
n = int(input())
print(descrever(n))
$PY_2$,
  'javascript', $JS_2$function descrever(n) {
  // TODO
}
[[ASCEND::RUNNER]]
const n = parseInt(require('fs').readFileSync(0, 'utf8').trim(), 10);
console.log(descrever(n));$JS_2$,
  'go', $GO_2$package main

import (
	"bufio"
	"fmt"
	"os"
)

func descrever(n int) string {
	// TODO
	return ""
}
[[ASCEND::RUNNER]]
func main() {
	reader := bufio.NewReader(os.Stdin)
	var n int
	fmt.Fscan(reader, &n)
	fmt.Println(descrever(n))
}$GO_2$
)
WHERE slug = 'trilha-n1-par-impar';

-- trilha-n1-inverte-caixa
UPDATE challenges
SET starter_code_by_language = jsonb_build_object(
  'python', $PY_3$def inverter_caixa(texto: str) -> str:
    pass

[[ASCEND::RUNNER]]
texto = input()
print(inverter_caixa(texto))
$PY_3$,
  'javascript', $JS_3$function inverter_caixa(texto) {
  // TODO
}
[[ASCEND::RUNNER]]
const texto = require('fs').readFileSync(0, 'utf8').split('\n')[0];
console.log(inverter_caixa(texto));$JS_3$,
  'go', $GO_3$package main

import (
	"bufio"
	"fmt"
	"os"
	"strings"
)

func inverter_caixa(texto string) string {
	// TODO
	return ""
}
[[ASCEND::RUNNER]]
func main() {
	reader := bufio.NewReader(os.Stdin)
	texto, _ := reader.ReadString('\n')
	texto = strings.TrimRight(texto, "\r\n")
	fmt.Println(inverter_caixa(texto))
}$GO_3$
)
WHERE slug = 'trilha-n1-inverte-caixa';

-- trilha-n1-area-circulo
UPDATE challenges
SET starter_code_by_language = jsonb_build_object(
  'python', $PY_4$import math

def area_circulo(r: float) -> float:
    pass

[[ASCEND::RUNNER]]
r = float(input())
print(f"{area_circulo(r):.2f}")
$PY_4$,
  'javascript', $JS_4$function area_circulo(r) {
  // TODO
}
[[ASCEND::RUNNER]]
const r = parseFloat(require('fs').readFileSync(0, 'utf8').trim());
console.log(area_circulo(r).toFixed(2));$JS_4$,
  'go', $GO_4$package main

import (
	"bufio"
	"fmt"
	"os"
)

func area_circulo(r float64) float64 {
	// TODO
	return 0
}
[[ASCEND::RUNNER]]
func main() {
	reader := bufio.NewReader(os.Stdin)
	var r float64
	fmt.Fscan(reader, &r)
	fmt.Printf("%.2f\n", area_circulo(r))
}$GO_4$
)
WHERE slug = 'trilha-n1-area-circulo';

-- trilha-n1-conversor-segundos
UPDATE challenges
SET starter_code_by_language = jsonb_build_object(
  'python', $PY_5$def converter(total_segundos: int) -> str:
    pass

[[ASCEND::RUNNER]]
total = int(input())
print(converter(total))
$PY_5$,
  'javascript', $JS_5$function converter(total_segundos) {
  // TODO
}
[[ASCEND::RUNNER]]
const total_segundos = parseInt(require('fs').readFileSync(0, 'utf8').trim(), 10);
console.log(converter(total_segundos));$JS_5$,
  'go', $GO_5$package main

import (
	"bufio"
	"fmt"
	"os"
)

func converter(total_segundos int) string {
	// TODO
	return ""
}
[[ASCEND::RUNNER]]
func main() {
	reader := bufio.NewReader(os.Stdin)
	var total int
	fmt.Fscan(reader, &total)
	fmt.Println(converter(total))
}$GO_5$
)
WHERE slug = 'trilha-n1-conversor-segundos';

-- trilha-n1-maioridade
UPDATE challenges
SET starter_code_by_language = jsonb_build_object(
  'python', $PY_6$def classificar(idade: int) -> str:
    pass

[[ASCEND::RUNNER]]
idade = int(input())
print(classificar(idade))
$PY_6$,
  'javascript', $JS_6$function classificar(idade) {
  // TODO
}
[[ASCEND::RUNNER]]
const idade = parseInt(require('fs').readFileSync(0, 'utf8').trim(), 10);
console.log(classificar(idade));$JS_6$,
  'go', $GO_6$package main

import (
	"bufio"
	"fmt"
	"os"
)

func classificar(idade int) string {
	// TODO
	return ""
}
[[ASCEND::RUNNER]]
func main() {
	reader := bufio.NewReader(os.Stdin)
	var idade int
	fmt.Fscan(reader, &idade)
	fmt.Println(classificar(idade))
}$GO_6$
)
WHERE slug = 'trilha-n1-maioridade';

-- trilha-n1-saudacao-turno
UPDATE challenges
SET starter_code_by_language = jsonb_build_object(
  'python', $PY_7$def saudacao(hora: int) -> str:
    pass

[[ASCEND::RUNNER]]
hora = int(input())
print(saudacao(hora))
$PY_7$,
  'javascript', $JS_7$function saudacao(hora) {
  // TODO
}
[[ASCEND::RUNNER]]
const hora = parseInt(require('fs').readFileSync(0, 'utf8').trim(), 10);
console.log(saudacao(hora));$JS_7$,
  'go', $GO_7$package main

import (
	"bufio"
	"fmt"
	"os"
)

func saudacao(hora int) string {
	// TODO
	return ""
}
[[ASCEND::RUNNER]]
func main() {
	reader := bufio.NewReader(os.Stdin)
	var hora int
	fmt.Fscan(reader, &hora)
	fmt.Println(saudacao(hora))
}$GO_7$
)
WHERE slug = 'trilha-n1-saudacao-turno';

-- trilha-n2-conta-palavras
UPDATE challenges
SET starter_code_by_language = jsonb_build_object(
  'python', $PY_8$def contar_palavras(frase: str) -> int:
    pass

[[ASCEND::RUNNER]]
frase = input()
print(contar_palavras(frase))
$PY_8$,
  'javascript', $JS_8$function contar_palavras(frase) {
  // TODO
}
[[ASCEND::RUNNER]]
const frase = require('fs').readFileSync(0, 'utf8').split('\n')[0];
console.log(contar_palavras(frase));$JS_8$,
  'go', $GO_8$package main

import (
	"bufio"
	"fmt"
	"os"
	"strings"
)

func contar_palavras(frase string) int {
	// TODO
	return 0
}
[[ASCEND::RUNNER]]
func main() {
	reader := bufio.NewReader(os.Stdin)
	frase, _ := reader.ReadString('\n')
	frase = strings.TrimRight(frase, "\r\n")
	fmt.Println(contar_palavras(frase))
}$GO_8$
)
WHERE slug = 'trilha-n2-conta-palavras';

-- trilha-n2-maior-sem-max
UPDATE challenges
SET starter_code_by_language = jsonb_build_object(
  'python', $PY_9$def maior(numeros: list[int]) -> int:
    pass

[[ASCEND::RUNNER]]
import sys
valores = [int(l) for l in sys.stdin.read().split()]
print(maior(valores))
$PY_9$,
  'javascript', $JS_9$function maior(numeros) {
  // TODO
}
[[ASCEND::RUNNER]]
const valores = require('fs').readFileSync(0, 'utf8').split(/\s+/).filter(Boolean).map(Number);
console.log(maior(valores));$JS_9$,
  'go', $GO_9$package main

import (
	"fmt"
	"io"
	"os"
	"strconv"
	"strings"
)

func maior(numeros []int) int {
	// TODO
	return 0
}
[[ASCEND::RUNNER]]
func main() {
	data, _ := io.ReadAll(os.Stdin)
	campos := strings.Fields(string(data))
	valores := make([]int, len(campos))
	for i, c := range campos {
		valores[i], _ = strconv.Atoi(c)
	}
	fmt.Println(maior(valores))
}$GO_9$
)
WHERE slug = 'trilha-n2-maior-sem-max';

-- trilha-n2-espacos-duplicados
UPDATE challenges
SET starter_code_by_language = jsonb_build_object(
  'python', $PY_10$def normalizar(texto: str) -> str:
    pass

[[ASCEND::RUNNER]]
texto = input()
print(normalizar(texto))
$PY_10$,
  'javascript', $JS_10$function normalizar(texto) {
  // TODO
}
[[ASCEND::RUNNER]]
const texto = require('fs').readFileSync(0, 'utf8').split('\n')[0];
console.log(normalizar(texto));$JS_10$,
  'go', $GO_10$package main

import (
	"bufio"
	"fmt"
	"os"
	"strings"
)

func normalizar(texto string) string {
	// TODO
	return ""
}
[[ASCEND::RUNNER]]
func main() {
	reader := bufio.NewReader(os.Stdin)
	texto, _ := reader.ReadString('\n')
	texto = strings.TrimRight(texto, "\r\n")
	fmt.Println(normalizar(texto))
}$GO_10$
)
WHERE slug = 'trilha-n2-espacos-duplicados';

-- trilha-n2-soma-pares
UPDATE challenges
SET starter_code_by_language = jsonb_build_object(
  'python', $PY_11$def soma_pares(numeros: list[int]) -> int:
    pass

[[ASCEND::RUNNER]]
import sys
valores = [int(l) for l in sys.stdin.read().split()]
print(soma_pares(valores))
$PY_11$,
  'javascript', $JS_11$function soma_pares(numeros) {
  // TODO
}
[[ASCEND::RUNNER]]
const valores = require('fs').readFileSync(0, 'utf8').split(/\s+/).filter(Boolean).map(Number);
console.log(soma_pares(valores));$JS_11$,
  'go', $GO_11$package main

import (
	"fmt"
	"io"
	"os"
	"strconv"
	"strings"
)

func soma_pares(numeros []int) int {
	// TODO
	return 0
}
[[ASCEND::RUNNER]]
func main() {
	data, _ := io.ReadAll(os.Stdin)
	campos := strings.Fields(string(data))
	valores := make([]int, len(campos))
	for i, c := range campos {
		valores[i], _ = strconv.Atoi(c)
	}
	fmt.Println(soma_pares(valores))
}$GO_11$
)
WHERE slug = 'trilha-n2-soma-pares';

-- trilha-n2-conta-letra
UPDATE challenges
SET starter_code_by_language = jsonb_build_object(
  'python', $PY_12$def contar_letra(frase: str, letra: str) -> int:
    pass

[[ASCEND::RUNNER]]
frase = input()
letra = input()
print(contar_letra(frase, letra))
$PY_12$,
  'javascript', $JS_12$function contar_letra(frase, letra) {
  // TODO
}
[[ASCEND::RUNNER]]
const __linhas = require('fs').readFileSync(0, 'utf8').split('\n');
const frase = __linhas[0];
const letra = __linhas[1];
console.log(contar_letra(frase, letra));$JS_12$,
  'go', $GO_12$package main

import (
	"bufio"
	"fmt"
	"os"
	"strings"
)

func contar_letra(frase string, letra string) int {
	// TODO
	return 0
}
[[ASCEND::RUNNER]]
func main() {
	reader := bufio.NewReader(os.Stdin)
	frase, _ := reader.ReadString('\n')
	frase = strings.TrimRight(frase, "\r\n")
	letra, _ := reader.ReadString('\n')
	letra = strings.TrimRight(letra, "\r\n")
	fmt.Println(contar_letra(frase, letra))
}$GO_12$
)
WHERE slug = 'trilha-n2-conta-letra';

-- trilha-n2-inverte-palavras
UPDATE challenges
SET starter_code_by_language = jsonb_build_object(
  'python', $PY_13$def inverter_palavras(frase: str) -> str:
    pass

[[ASCEND::RUNNER]]
frase = input()
print(inverter_palavras(frase))
$PY_13$,
  'javascript', $JS_13$function inverter_palavras(frase) {
  // TODO
}
[[ASCEND::RUNNER]]
const frase = require('fs').readFileSync(0, 'utf8').split('\n')[0];
console.log(inverter_palavras(frase));$JS_13$,
  'go', $GO_13$package main

import (
	"bufio"
	"fmt"
	"os"
	"strings"
)

func inverter_palavras(frase string) string {
	// TODO
	return ""
}
[[ASCEND::RUNNER]]
func main() {
	reader := bufio.NewReader(os.Stdin)
	frase, _ := reader.ReadString('\n')
	frase = strings.TrimRight(frase, "\r\n")
	fmt.Println(inverter_palavras(frase))
}$GO_13$
)
WHERE slug = 'trilha-n2-inverte-palavras';

-- trilha-n2-media-sem-extremos
UPDATE challenges
SET starter_code_by_language = jsonb_build_object(
  'python', $PY_14$def media_sem_extremos(numeros: list[int]) -> float:
    pass

[[ASCEND::RUNNER]]
import sys
valores = [int(l) for l in sys.stdin.read().split()]
print(f"{media_sem_extremos(valores):.2f}")
$PY_14$,
  'javascript', $JS_14$function media_sem_extremos(numeros) {
  // TODO
}
[[ASCEND::RUNNER]]
const valores = require('fs').readFileSync(0, 'utf8').split(/\s+/).filter(Boolean).map(Number);
console.log(media_sem_extremos(valores).toFixed(2));$JS_14$,
  'go', $GO_14$package main

import (
	"fmt"
	"io"
	"os"
	"strconv"
	"strings"
)

func media_sem_extremos(numeros []int) float64 {
	// TODO
	return 0
}
[[ASCEND::RUNNER]]
func main() {
	data, _ := io.ReadAll(os.Stdin)
	campos := strings.Fields(string(data))
	valores := make([]int, len(campos))
	for i, c := range campos {
		valores[i], _ = strconv.Atoi(c)
	}
	fmt.Printf("%.2f\n", media_sem_extremos(valores))
}$GO_14$
)
WHERE slug = 'trilha-n2-media-sem-extremos';

-- trilha-n3-anagrama
UPDATE challenges
SET starter_code_by_language = jsonb_build_object(
  'python', $PY_15$def eh_anagrama(a: str, b: str) -> bool:
    pass

[[ASCEND::RUNNER]]
a = input()
b = input()
print("sim" if eh_anagrama(a, b) else "nao")
$PY_15$,
  'javascript', $JS_15$function eh_anagrama(a, b) {
  // TODO
}
[[ASCEND::RUNNER]]
const __linhas = require('fs').readFileSync(0, 'utf8').split('\n');
const a = __linhas[0];
const b = __linhas[1];
console.log(eh_anagrama(a, b) ? 'sim' : 'nao');$JS_15$,
  'go', $GO_15$package main

import (
	"bufio"
	"fmt"
	"os"
	"strings"
)

func eh_anagrama(a string, b string) bool {
	// TODO
	return false
}
[[ASCEND::RUNNER]]
func main() {
	reader := bufio.NewReader(os.Stdin)
	a, _ := reader.ReadString('\n')
	a = strings.TrimRight(a, "\r\n")
	b, _ := reader.ReadString('\n')
	b = strings.TrimRight(b, "\r\n")
	if eh_anagrama(a, b) {
		fmt.Println("sim")
	} else {
		fmt.Println("nao")
	}
}$GO_15$
)
WHERE slug = 'trilha-n3-anagrama';

-- trilha-n3-mais-frequente
UPDATE challenges
SET starter_code_by_language = jsonb_build_object(
  'python', $PY_16$def mais_frequente(numeros: list[int]) -> int:
    pass

[[ASCEND::RUNNER]]
import sys
valores = [int(l) for l in sys.stdin.read().split()]
print(mais_frequente(valores))
$PY_16$,
  'javascript', $JS_16$function mais_frequente(numeros) {
  // TODO
}
[[ASCEND::RUNNER]]
const valores = require('fs').readFileSync(0, 'utf8').split(/\s+/).filter(Boolean).map(Number);
console.log(mais_frequente(valores));$JS_16$,
  'go', $GO_16$package main

import (
	"fmt"
	"io"
	"os"
	"strconv"
	"strings"
)

func mais_frequente(numeros []int) int {
	// TODO
	return 0
}
[[ASCEND::RUNNER]]
func main() {
	data, _ := io.ReadAll(os.Stdin)
	campos := strings.Fields(string(data))
	valores := make([]int, len(campos))
	for i, c := range campos {
		valores[i], _ = strconv.Atoi(c)
	}
	fmt.Println(mais_frequente(valores))
}$GO_16$
)
WHERE slug = 'trilha-n3-mais-frequente';

-- trilha-n3-estatistica-lista
UPDATE challenges
SET starter_code_by_language = jsonb_build_object(
  'python', $PY_17$class Estatistica:
    def __init__(self, numeros: list[int]):
        self.numeros = numeros

    def media(self) -> float:
        pass

    def mediana(self) -> float:
        pass

    def moda(self) -> int:
        pass

[[ASCEND::RUNNER]]
import sys
valores = [int(l) for l in sys.stdin.read().split()]
e = Estatistica(valores)
print(f"{e.media():.2f}")
print(f"{e.mediana():.2f}")
print(e.moda())
$PY_17$,
  'javascript', $JS_17$class Estatistica {
  constructor(numeros) {
    this.numeros = numeros;
  }

  media() {
    // TODO
  }

  mediana() {
    // TODO
  }

  moda() {
    // TODO
  }
}
[[ASCEND::RUNNER]]
const valores = require('fs').readFileSync(0, 'utf8').split(/\s+/).filter(Boolean).map(Number);
const e = new Estatistica(valores);
console.log(e.media().toFixed(2));
console.log(e.mediana().toFixed(2));
console.log(e.moda());$JS_17$,
  'go', $GO_17$package main

import (
	"fmt"
	"io"
	"os"
	"strconv"
	"strings"
)

type Estatistica struct {
	numeros []int
}

func NovaEstatistica(numeros []int) *Estatistica {
	return &Estatistica{numeros: numeros}
}

func (e *Estatistica) media() float64 {
	// TODO
	return 0
}

func (e *Estatistica) mediana() float64 {
	// TODO
	return 0
}

func (e *Estatistica) moda() int {
	// TODO
	return 0
}
[[ASCEND::RUNNER]]
func main() {
	data, _ := io.ReadAll(os.Stdin)
	campos := strings.Fields(string(data))
	valores := make([]int, len(campos))
	for i, c := range campos {
		valores[i], _ = strconv.Atoi(c)
	}
	e := NovaEstatistica(valores)
	fmt.Printf("%.2f\n", e.media())
	fmt.Printf("%.2f\n", e.mediana())
	fmt.Println(e.moda())
}$GO_17$
)
WHERE slug = 'trilha-n3-estatistica-lista';

-- trilha-n3-conta-caracteres
UPDATE challenges
SET starter_code_by_language = jsonb_build_object(
  'python', $PY_18$def contar_caracteres(palavra: str) -> str:
    pass

[[ASCEND::RUNNER]]
palavra = input()
print(contar_caracteres(palavra))
$PY_18$,
  'javascript', $JS_18$function contar_caracteres(palavra) {
  // TODO
}
[[ASCEND::RUNNER]]
const palavra = require('fs').readFileSync(0, 'utf8').split('\n')[0];
console.log(contar_caracteres(palavra));$JS_18$,
  'go', $GO_18$package main

import (
	"bufio"
	"fmt"
	"os"
	"strings"
)

func contar_caracteres(palavra string) string {
	// TODO
	return ""
}
[[ASCEND::RUNNER]]
func main() {
	reader := bufio.NewReader(os.Stdin)
	palavra, _ := reader.ReadString('\n')
	palavra = strings.TrimRight(palavra, "\r\n")
	fmt.Println(contar_caracteres(palavra))
}$GO_18$
)
WHERE slug = 'trilha-n3-conta-caracteres';

-- trilha-n3-fusao-dicionarios
UPDATE challenges
SET starter_code_by_language = jsonb_build_object(
  'python', $PY_19$def fundir(dict1: dict, dict2: dict) -> dict:
    pass

[[ASCEND::RUNNER]]
n1 = int(input())
d1 = {}
for _ in range(n1):
    k, v = input().split()
    d1[k] = int(v)
n2 = int(input())
d2 = {}
for _ in range(n2):
    k, v = input().split()
    d2[k] = int(v)
resultado = fundir(d1, d2)
print(' '.join(f"{k}:{resultado[k]}" for k in sorted(resultado)))
$PY_19$,
  'javascript', $JS_19$function fundir(dict1, dict2) {
  // TODO
}
[[ASCEND::RUNNER]]
const __linhas = require('fs').readFileSync(0, 'utf8').split('\n');
let __i = 0;
const n1 = parseInt(__linhas[__i++], 10);
const d1 = {};
for (let j = 0; j < n1; j++) {
  const [k, v] = __linhas[__i++].split(' ');
  d1[k] = parseInt(v, 10);
}
const n2 = parseInt(__linhas[__i++], 10);
const d2 = {};
for (let j = 0; j < n2; j++) {
  const [k, v] = __linhas[__i++].split(' ');
  d2[k] = parseInt(v, 10);
}
const resultado = fundir(d1, d2);
console.log(Object.keys(resultado).sort().map(k => `${k}:${resultado[k]}`).join(' '));$JS_19$,
  'go', $GO_19$package main

import (
	"bufio"
	"fmt"
	"os"
	"sort"
	"strings"
)

func fundir(dict1 map[string]int, dict2 map[string]int) map[string]int {
	// TODO
	return nil
}
[[ASCEND::RUNNER]]
func main() {
	reader := bufio.NewReader(os.Stdin)
	var n1 int
	fmt.Fscan(reader, &n1)
	d1 := make(map[string]int)
	for i := 0; i < n1; i++ {
		var k string
		var v int
		fmt.Fscan(reader, &k, &v)
		d1[k] = v
	}
	var n2 int
	fmt.Fscan(reader, &n2)
	d2 := make(map[string]int)
	for i := 0; i < n2; i++ {
		var k string
		var v int
		fmt.Fscan(reader, &k, &v)
		d2[k] = v
	}
	resultado := fundir(d1, d2)
	chaves := make([]string, 0, len(resultado))
	for k := range resultado {
		chaves = append(chaves, k)
	}
	sort.Strings(chaves)
	partes := make([]string, len(chaves))
	for i, k := range chaves {
		partes[i] = fmt.Sprintf("%s:%d", k, resultado[k])
	}
	fmt.Println(strings.Join(partes, " "))
}$GO_19$
)
WHERE slug = 'trilha-n3-fusao-dicionarios';

-- trilha-n3-fila-fifo
UPDATE challenges
SET starter_code_by_language = jsonb_build_object(
  'python', $PY_20$class FilaAtendimento:
    def __init__(self):
        self.fila = []

    def chegar(self, nome: str) -> None:
        pass

    def atender(self) -> None:
        pass

[[ASCEND::RUNNER]]
import sys
fila = FilaAtendimento()
for linha in sys.stdin.read().split('\n'):
    if not linha.strip():
        continue
    partes = linha.split()
    if partes[0] == "CHEGAR":
        fila.chegar(partes[1])
    elif partes[0] == "ATENDER":
        fila.atender()
$PY_20$,
  'javascript', $JS_20$class FilaAtendimento {
  constructor() {
    this.fila = [];
  }

  chegar(nome) {
    // TODO
  }

  atender() {
    // TODO
  }
}
[[ASCEND::RUNNER]]
const linhas = require('fs').readFileSync(0, 'utf8').split('\n');
const fila = new FilaAtendimento();
for (const linha of linhas) {
  if (!linha.trim()) continue;
  const partes = linha.split(/\s+/);
  if (partes[0] === 'CHEGAR') {
    fila.chegar(partes[1]);
  } else if (partes[0] === 'ATENDER') {
    fila.atender();
  }
}$JS_20$,
  'go', $GO_20$package main

import (
	"io"
	"os"
	"strings"
)

type FilaAtendimento struct {
	fila []string
}

func NovaFilaAtendimento() *FilaAtendimento {
	return &FilaAtendimento{}
}

func (f *FilaAtendimento) chegar(nome string) {
	// TODO
}

func (f *FilaAtendimento) atender() {
	// TODO
}
[[ASCEND::RUNNER]]
func main() {
	data, _ := io.ReadAll(os.Stdin)
	linhas := strings.Split(string(data), "\n")
	fila := NovaFilaAtendimento()
	for _, linha := range linhas {
		if strings.TrimSpace(linha) == "" {
			continue
		}
		partes := strings.Fields(linha)
		switch partes[0] {
		case "CHEGAR":
			fila.chegar(partes[1])
		case "ATENDER":
			fila.atender()
		}
	}
}$GO_20$
)
WHERE slug = 'trilha-n3-fila-fifo';

-- trilha-n3-formato-cpf
UPDATE challenges
SET starter_code_by_language = jsonb_build_object(
  'python', $PY_21$def formato_valido(cpf: str) -> bool:
    pass

[[ASCEND::RUNNER]]
cpf = input()
print("formato valido" if formato_valido(cpf) else "formato invalido")
$PY_21$,
  'javascript', $JS_21$function formato_valido(cpf) {
  // TODO
}
[[ASCEND::RUNNER]]
const cpf = require('fs').readFileSync(0, 'utf8').split('\n')[0];
console.log(formato_valido(cpf) ? 'formato valido' : 'formato invalido');$JS_21$,
  'go', $GO_21$package main

import (
	"bufio"
	"fmt"
	"os"
	"strings"
)

func formato_valido(cpf string) bool {
	// TODO
	return false
}
[[ASCEND::RUNNER]]
func main() {
	reader := bufio.NewReader(os.Stdin)
	cpf, _ := reader.ReadString('\n')
	cpf = strings.TrimRight(cpf, "\r\n")
	if formato_valido(cpf) {
		fmt.Println("formato valido")
	} else {
		fmt.Println("formato invalido")
	}
}$GO_21$
)
WHERE slug = 'trilha-n3-formato-cpf';

-- trilha-n4-linha-sudoku
UPDATE challenges
SET starter_code_by_language = jsonb_build_object(
  'python', $PY_22$def validar_linha(numeros: list[int]) -> bool:
    pass

[[ASCEND::RUNNER]]
numeros = list(map(int, input().split()))
print("valido" if validar_linha(numeros) else "invalido")
$PY_22$,
  'javascript', $JS_22$function validar_linha(numeros) {
  // TODO
}
[[ASCEND::RUNNER]]
const numeros = require('fs').readFileSync(0, 'utf8').trim().split(/\s+/).map(Number);
console.log(validar_linha(numeros) ? 'valido' : 'invalido');$JS_22$,
  'go', $GO_22$package main

import (
	"bufio"
	"fmt"
	"os"
	"strconv"
	"strings"
)

func validar_linha(numeros []int) bool {
	// TODO
	return false
}
[[ASCEND::RUNNER]]
func main() {
	reader := bufio.NewReader(os.Stdin)
	linha, _ := reader.ReadString('\n')
	linha = strings.TrimRight(linha, "\r\n")
	campos := strings.Fields(linha)
	numeros := make([]int, len(campos))
	for i, c := range campos {
		numeros[i], _ = strconv.Atoi(c)
	}
	if validar_linha(numeros) {
		fmt.Println("valido")
	} else {
		fmt.Println("invalido")
	}
}$GO_22$
)
WHERE slug = 'trilha-n4-linha-sudoku';

-- trilha-n4-parenteses-multiplos
UPDATE challenges
SET starter_code_by_language = jsonb_build_object(
  'python', $PY_23$def esta_balanceado(texto: str) -> bool:
    pass

[[ASCEND::RUNNER]]
texto = input()
print("balanceado" if esta_balanceado(texto) else "desbalanceado")
$PY_23$,
  'javascript', $JS_23$function esta_balanceado(texto) {
  // TODO
}
[[ASCEND::RUNNER]]
const texto = require('fs').readFileSync(0, 'utf8').split('\n')[0];
console.log(esta_balanceado(texto) ? 'balanceado' : 'desbalanceado');$JS_23$,
  'go', $GO_23$package main

import (
	"bufio"
	"fmt"
	"os"
	"strings"
)

func esta_balanceado(texto string) bool {
	// TODO
	return false
}
[[ASCEND::RUNNER]]
func main() {
	reader := bufio.NewReader(os.Stdin)
	texto, _ := reader.ReadString('\n')
	texto = strings.TrimRight(texto, "\r\n")
	if esta_balanceado(texto) {
		fmt.Println("balanceado")
	} else {
		fmt.Println("desbalanceado")
	}
}$GO_23$
)
WHERE slug = 'trilha-n4-parenteses-multiplos';

-- trilha-n4-rle
UPDATE challenges
SET starter_code_by_language = jsonb_build_object(
  'python', $PY_24$def comprimir(texto: str) -> str:
    pass

[[ASCEND::RUNNER]]
texto = input()
print(comprimir(texto))
$PY_24$,
  'javascript', $JS_24$function comprimir(texto) {
  // TODO
}
[[ASCEND::RUNNER]]
const texto = require('fs').readFileSync(0, 'utf8').split('\n')[0];
console.log(comprimir(texto));$JS_24$,
  'go', $GO_24$package main

import (
	"bufio"
	"fmt"
	"os"
	"strings"
)

func comprimir(texto string) string {
	// TODO
	return ""
}
[[ASCEND::RUNNER]]
func main() {
	reader := bufio.NewReader(os.Stdin)
	texto, _ := reader.ReadString('\n')
	texto = strings.TrimRight(texto, "\r\n")
	fmt.Println(comprimir(texto))
}$GO_24$
)
WHERE slug = 'trilha-n4-rle';

-- trilha-n4-carrinho-desconto
UPDATE challenges
SET starter_code_by_language = jsonb_build_object(
  'python', $PY_25$class Carrinho:
    def __init__(self):
        self.itens = []

    def adicionar(self, produto: str, preco: float) -> None:
        pass

    def total(self) -> None:
        pass

[[ASCEND::RUNNER]]
import sys
carrinho = Carrinho()
for linha in sys.stdin.read().split('\n'):
    if not linha.strip():
        continue
    partes = linha.split()
    if partes[0] == "ADICIONAR":
        carrinho.adicionar(partes[1], float(partes[2]))
    elif partes[0] == "TOTAL":
        carrinho.total()
$PY_25$,
  'javascript', $JS_25$class Carrinho {
  constructor() {
    this.itens = [];
  }

  adicionar(produto, preco) {
    // TODO
  }

  total() {
    // TODO
  }
}
[[ASCEND::RUNNER]]
const linhas = require('fs').readFileSync(0, 'utf8').split('\n');
const carrinho = new Carrinho();
for (const linha of linhas) {
  if (!linha.trim()) continue;
  const partes = linha.split(/\s+/);
  if (partes[0] === 'ADICIONAR') {
    carrinho.adicionar(partes[1], parseFloat(partes[2]));
  } else if (partes[0] === 'TOTAL') {
    carrinho.total();
  }
}$JS_25$,
  'go', $GO_25$package main

import (
	"io"
	"os"
	"strconv"
	"strings"
)

type Carrinho struct {
	itens []float64
}

func NovoCarrinho() *Carrinho {
	return &Carrinho{}
}

func (c *Carrinho) adicionar(produto string, preco float64) {
	// TODO
}

func (c *Carrinho) total() {
	// TODO
}
[[ASCEND::RUNNER]]
func main() {
	data, _ := io.ReadAll(os.Stdin)
	linhas := strings.Split(string(data), "\n")
	carrinho := NovoCarrinho()
	for _, linha := range linhas {
		if strings.TrimSpace(linha) == "" {
			continue
		}
		partes := strings.Fields(linha)
		switch partes[0] {
		case "ADICIONAR":
			preco, _ := strconv.ParseFloat(partes[2], 64)
			carrinho.adicionar(partes[1], preco)
		case "TOTAL":
			carrinho.total()
		}
	}
}$GO_25$
)
WHERE slug = 'trilha-n4-carrinho-desconto';

-- trilha-n4-grau-conexoes
UPDATE challenges
SET starter_code_by_language = jsonb_build_object(
  'python', $PY_26$class RedeAmigos:
    def __init__(self):
        self.conexoes = {}

    def conectar(self, a: str, b: str) -> None:
        pass

    def grau(self, pessoa: str) -> None:
        pass

[[ASCEND::RUNNER]]
import sys
rede = RedeAmigos()
for linha in sys.stdin.read().split('\n'):
    if not linha.strip():
        continue
    partes = linha.split()
    if partes[0] == "CONECTAR":
        rede.conectar(partes[1], partes[2])
    elif partes[0] == "GRAU":
        rede.grau(partes[1])
$PY_26$,
  'javascript', $JS_26$class RedeAmigos {
  constructor() {
    this.conexoes = {};
  }

  conectar(a, b) {
    // TODO
  }

  grau(pessoa) {
    // TODO
  }
}
[[ASCEND::RUNNER]]
const linhas = require('fs').readFileSync(0, 'utf8').split('\n');
const rede = new RedeAmigos();
for (const linha of linhas) {
  if (!linha.trim()) continue;
  const partes = linha.split(/\s+/);
  if (partes[0] === 'CONECTAR') {
    rede.conectar(partes[1], partes[2]);
  } else if (partes[0] === 'GRAU') {
    rede.grau(partes[1]);
  }
}$JS_26$,
  'go', $GO_26$package main

import (
	"io"
	"os"
	"strings"
)

type RedeAmigos struct {
	conexoes map[string]map[string]bool
}

func NovaRedeAmigos() *RedeAmigos {
	return &RedeAmigos{conexoes: make(map[string]map[string]bool)}
}

func (r *RedeAmigos) conectar(a string, b string) {
	// TODO
}

func (r *RedeAmigos) grau(pessoa string) {
	// TODO
}
[[ASCEND::RUNNER]]
func main() {
	data, _ := io.ReadAll(os.Stdin)
	linhas := strings.Split(string(data), "\n")
	rede := NovaRedeAmigos()
	for _, linha := range linhas {
		if strings.TrimSpace(linha) == "" {
			continue
		}
		partes := strings.Fields(linha)
		switch partes[0] {
		case "CONECTAR":
			rede.conectar(partes[1], partes[2])
		case "GRAU":
			rede.grau(partes[1])
		}
	}
}$GO_26$
)
WHERE slug = 'trilha-n4-grau-conexoes';

-- trilha-n4-matriz-magica
UPDATE challenges
SET starter_code_by_language = jsonb_build_object(
  'python', $PY_27$def eh_magica(matriz: list[list[int]]) -> bool:
    pass

[[ASCEND::RUNNER]]
n = int(input())
matriz = [list(map(int, input().split())) for _ in range(n)]
print("magica" if eh_magica(matriz) else "nao magica")
$PY_27$,
  'javascript', $JS_27$function eh_magica(matriz) {
  // TODO
}
[[ASCEND::RUNNER]]
const __linhas = require('fs').readFileSync(0, 'utf8').split('\n');
const n = parseInt(__linhas[0], 10);
const matriz = [];
for (let i = 0; i < n; i++) {
  matriz.push(__linhas[i + 1].trim().split(/\s+/).map(Number));
}
console.log(eh_magica(matriz) ? 'magica' : 'nao magica');$JS_27$,
  'go', $GO_27$package main

import (
	"bufio"
	"fmt"
	"os"
)

func eh_magica(matriz [][]int) bool {
	// TODO
	return false
}
[[ASCEND::RUNNER]]
func main() {
	reader := bufio.NewReader(os.Stdin)
	var n int
	fmt.Fscan(reader, &n)
	matriz := make([][]int, n)
	for i := 0; i < n; i++ {
		matriz[i] = make([]int, n)
		for j := 0; j < n; j++ {
			fmt.Fscan(reader, &matriz[i][j])
		}
	}
	if eh_magica(matriz) {
		fmt.Println("magica")
	} else {
		fmt.Println("nao magica")
	}
}$GO_27$
)
WHERE slug = 'trilha-n4-matriz-magica';

-- trilha-n4-fila-impressao-prioridade
UPDATE challenges
SET starter_code_by_language = jsonb_build_object(
  'python', $PY_28$class FilaImpressao:
    def __init__(self):
        self.prioritarias = []
        self.normais = []

    def imprimir(self, nome: str, tipo: str) -> None:
        pass

    def proximo(self) -> None:
        pass

[[ASCEND::RUNNER]]
import sys
fila = FilaImpressao()
for linha in sys.stdin.read().split('\n'):
    if not linha.strip():
        continue
    partes = linha.split()
    if partes[0] == "IMPRIMIR":
        fila.imprimir(partes[1], partes[2])
    elif partes[0] == "PROXIMO":
        fila.proximo()
$PY_28$,
  'javascript', $JS_28$class FilaImpressao {
  constructor() {
    this.prioritarias = [];
    this.normais = [];
  }

  imprimir(nome, tipo) {
    // TODO
  }

  proximo() {
    // TODO
  }
}
[[ASCEND::RUNNER]]
const linhas = require('fs').readFileSync(0, 'utf8').split('\n');
const fila = new FilaImpressao();
for (const linha of linhas) {
  if (!linha.trim()) continue;
  const partes = linha.split(/\s+/);
  if (partes[0] === 'IMPRIMIR') {
    fila.imprimir(partes[1], partes[2]);
  } else if (partes[0] === 'PROXIMO') {
    fila.proximo();
  }
}$JS_28$,
  'go', $GO_28$package main

import (
	"io"
	"os"
	"strings"
)

type FilaImpressao struct {
	prioritarias []string
	normais      []string
}

func NovaFilaImpressao() *FilaImpressao {
	return &FilaImpressao{}
}

func (f *FilaImpressao) imprimir(nome string, tipo string) {
	// TODO
}

func (f *FilaImpressao) proximo() {
	// TODO
}
[[ASCEND::RUNNER]]
func main() {
	data, _ := io.ReadAll(os.Stdin)
	linhas := strings.Split(string(data), "\n")
	fila := NovaFilaImpressao()
	for _, linha := range linhas {
		if strings.TrimSpace(linha) == "" {
			continue
		}
		partes := strings.Fields(linha)
		switch partes[0] {
		case "IMPRIMIR":
			fila.imprimir(partes[1], partes[2])
		case "PROXIMO":
			fila.proximo()
		}
	}
}$GO_28$
)
WHERE slug = 'trilha-n4-fila-impressao-prioridade';

-- trilha-n5-estoque-validacao
UPDATE challenges
SET starter_code_by_language = jsonb_build_object(
  'python', $PY_29$class Estoque:
    def __init__(self):
        self.produtos = {}

    def entrada(self, produto: str, quantidade: int) -> None:
        pass

    def saida(self, produto: str, quantidade: int) -> None:
        pass

    def consultar(self, produto: str) -> None:
        pass

[[ASCEND::RUNNER]]
import sys
estoque = Estoque()
for linha in sys.stdin.read().split('\n'):
    if not linha.strip():
        continue
    partes = linha.split()
    if partes[0] == "ENTRADA":
        estoque.entrada(partes[1], int(partes[2]))
    elif partes[0] == "SAIDA":
        estoque.saida(partes[1], int(partes[2]))
    elif partes[0] == "CONSULTAR":
        estoque.consultar(partes[1])
$PY_29$,
  'javascript', $JS_29$class Estoque {
  constructor() {
    this.produtos = {};
  }

  entrada(produto, quantidade) {
    // TODO
  }

  saida(produto, quantidade) {
    // TODO
  }

  consultar(produto) {
    // TODO
  }
}
[[ASCEND::RUNNER]]
const linhas = require('fs').readFileSync(0, 'utf8').split('\n');
const estoque = new Estoque();
for (const linha of linhas) {
  if (!linha.trim()) continue;
  const partes = linha.split(/\s+/);
  if (partes[0] === 'ENTRADA') {
    estoque.entrada(partes[1], parseInt(partes[2], 10));
  } else if (partes[0] === 'SAIDA') {
    estoque.saida(partes[1], parseInt(partes[2], 10));
  } else if (partes[0] === 'CONSULTAR') {
    estoque.consultar(partes[1]);
  }
}$JS_29$,
  'go', $GO_29$package main

import (
	"io"
	"os"
	"strconv"
	"strings"
)

type Estoque struct {
	produtos map[string]int
}

func NovoEstoque() *Estoque {
	return &Estoque{produtos: make(map[string]int)}
}

func (e *Estoque) entrada(produto string, quantidade int) {
	// TODO
}

func (e *Estoque) saida(produto string, quantidade int) {
	// TODO
}

func (e *Estoque) consultar(produto string) {
	// TODO
}
[[ASCEND::RUNNER]]
func main() {
	data, _ := io.ReadAll(os.Stdin)
	linhas := strings.Split(string(data), "\n")
	estoque := NovoEstoque()
	for _, linha := range linhas {
		if strings.TrimSpace(linha) == "" {
			continue
		}
		partes := strings.Fields(linha)
		switch partes[0] {
		case "ENTRADA":
			q, _ := strconv.Atoi(partes[2])
			estoque.entrada(partes[1], q)
		case "SAIDA":
			q, _ := strconv.Atoi(partes[2])
			estoque.saida(partes[1], q)
		case "CONSULTAR":
			estoque.consultar(partes[1])
		}
	}
}$GO_29$
)
WHERE slug = 'trilha-n5-estoque-validacao';

-- trilha-n5-escola-aninhada
UPDATE challenges
SET starter_code_by_language = jsonb_build_object(
  'python', $PY_30$def media_aluno(notas: list[float]) -> float:
    pass

def media_turma(medias_alunos: list[float]) -> float:
    pass

[[ASCEND::RUNNER]]
import sys
linhas = sys.stdin.read().split('\n')
i = 0
n_turmas = int(linhas[i]); i += 1
for _ in range(n_turmas):
    nome_turma = linhas[i]; i += 1
    n_alunos = int(linhas[i]); i += 1
    medias = []
    for _ in range(n_alunos):
        partes = linhas[i].split(); i += 1
        notas = list(map(float, partes[1:]))
        medias.append(media_aluno(notas))
    print(f"{nome_turma}: {media_turma(medias):.2f}")
$PY_30$,
  'javascript', $JS_30$function media_aluno(notas) {
  // TODO
}

function media_turma(medias_alunos) {
  // TODO
}
[[ASCEND::RUNNER]]
const linhas = require('fs').readFileSync(0, 'utf8').split('\n');
let i = 0;
const n_turmas = parseInt(linhas[i++], 10);
for (let t = 0; t < n_turmas; t++) {
  const nome_turma = linhas[i++];
  const n_alunos = parseInt(linhas[i++], 10);
  const medias = [];
  for (let a = 0; a < n_alunos; a++) {
    const partes = linhas[i++].trim().split(/\s+/);
    const notas = partes.slice(1).map(Number);
    medias.push(media_aluno(notas));
  }
  console.log(`${nome_turma}: ${media_turma(medias).toFixed(2)}`);
}$JS_30$,
  'go', $GO_30$package main

import (
	"fmt"
	"io"
	"os"
	"strconv"
	"strings"
)

func media_aluno(notas []float64) float64 {
	// TODO
	return 0
}

func media_turma(mediasAlunos []float64) float64 {
	// TODO
	return 0
}
[[ASCEND::RUNNER]]
func main() {
	data, _ := io.ReadAll(os.Stdin)
	linhas := strings.Split(string(data), "\n")
	i := 0
	nTurmas, _ := strconv.Atoi(linhas[i])
	i++
	for t := 0; t < nTurmas; t++ {
		nomeTurma := linhas[i]
		i++
		nAlunos, _ := strconv.Atoi(linhas[i])
		i++
		medias := make([]float64, 0, nAlunos)
		for a := 0; a < nAlunos; a++ {
			partes := strings.Fields(linhas[i])
			i++
			notas := make([]float64, len(partes)-1)
			for k, p := range partes[1:] {
				notas[k], _ = strconv.ParseFloat(p, 64)
			}
			medias = append(medias, media_aluno(notas))
		}
		fmt.Printf("%s: %.2f\n", nomeTurma, media_turma(medias))
	}
}$GO_30$
)
WHERE slug = 'trilha-n5-escola-aninhada';

-- trilha-n5-cache-capacidade
UPDATE challenges
SET starter_code_by_language = jsonb_build_object(
  'python', $PY_31$class CacheSimples:
    def __init__(self, capacidade: int):
        self.capacidade = capacidade
        self.itens = []

    def adicionar(self, item: str) -> None:
        pass

    def listar(self) -> None:
        pass

[[ASCEND::RUNNER]]
import sys
linhas = sys.stdin.read().split('\n')
capacidade = int(linhas[0])
cache = CacheSimples(capacidade)
for linha in linhas[1:]:
    if not linha.strip():
        continue
    partes = linha.split()
    if partes[0] == "ADICIONAR":
        cache.adicionar(partes[1])
    elif partes[0] == "LISTAR":
        cache.listar()
$PY_31$,
  'javascript', $JS_31$class CacheSimples {
  constructor(capacidade) {
    this.capacidade = capacidade;
    this.itens = [];
  }

  adicionar(item) {
    // TODO
  }

  listar() {
    // TODO
  }
}
[[ASCEND::RUNNER]]
const linhas = require('fs').readFileSync(0, 'utf8').split('\n');
const capacidade = parseInt(linhas[0], 10);
const cache = new CacheSimples(capacidade);
for (const linha of linhas.slice(1)) {
  if (!linha.trim()) continue;
  const partes = linha.split(/\s+/);
  if (partes[0] === 'ADICIONAR') {
    cache.adicionar(partes[1]);
  } else if (partes[0] === 'LISTAR') {
    cache.listar();
  }
}$JS_31$,
  'go', $GO_31$package main

import (
	"io"
	"os"
	"strconv"
	"strings"
)

type CacheSimples struct {
	capacidade int
	itens      []string
}

func NovoCacheSimples(capacidade int) *CacheSimples {
	return &CacheSimples{capacidade: capacidade}
}

func (c *CacheSimples) adicionar(item string) {
	// TODO
}

func (c *CacheSimples) listar() {
	// TODO
}
[[ASCEND::RUNNER]]
func main() {
	data, _ := io.ReadAll(os.Stdin)
	linhas := strings.Split(string(data), "\n")
	capacidade, _ := strconv.Atoi(linhas[0])
	cache := NovoCacheSimples(capacidade)
	for _, linha := range linhas[1:] {
		if strings.TrimSpace(linha) == "" {
			continue
		}
		partes := strings.Fields(linha)
		switch partes[0] {
		case "ADICIONAR":
			cache.adicionar(partes[1])
		case "LISTAR":
			cache.listar()
		}
	}
}$GO_31$
)
WHERE slug = 'trilha-n5-cache-capacidade';

-- trilha-n5-classificador-times
UPDATE challenges
SET starter_code_by_language = jsonb_build_object(
  'python', $PY_32$class Campeonato:
    def __init__(self, times: list[str]):
        self.pontos = {t: 0 for t in times}

    def registrar_resultado(self, time_a: str, time_b: str, gols_a: int, gols_b: int) -> None:
        pass

    def ranking(self) -> list[tuple[str, int]]:
        pass

[[ASCEND::RUNNER]]
n_times = int(input())
times = [input() for _ in range(n_times)]
campeonato = Campeonato(times)
n_resultados = int(input())
for _ in range(n_resultados):
    a, b, ga, gb = input().split()
    campeonato.registrar_resultado(a, b, int(ga), int(gb))
for time, pontos in campeonato.ranking():
    print(f"{time}:{pontos}")
$PY_32$,
  'javascript', $JS_32$class Campeonato {
  constructor(times) {
    this.ordem = times;
    this.pontos = {};
    for (const t of times) this.pontos[t] = 0;
  }

  registrar_resultado(time_a, time_b, gols_a, gols_b) {
    // TODO
  }

  ranking() {
    // TODO
  }
}
[[ASCEND::RUNNER]]
const linhas = require('fs').readFileSync(0, 'utf8').split('\n');
let i = 0;
const n_times = parseInt(linhas[i++], 10);
const times = [];
for (let t = 0; t < n_times; t++) times.push(linhas[i++]);
const campeonato = new Campeonato(times);
const n_resultados = parseInt(linhas[i++], 10);
for (let r = 0; r < n_resultados; r++) {
  const [a, b, ga, gb] = linhas[i++].trim().split(/\s+/);
  campeonato.registrar_resultado(a, b, parseInt(ga, 10), parseInt(gb, 10));
}
for (const [time, pontos] of campeonato.ranking()) {
  console.log(`${time}:${pontos}`);
}$JS_32$,
  'go', $GO_32$package main

import (
	"bufio"
	"fmt"
	"os"
	"strings"
)

type ResultadoRanking struct {
	Time   string
	Pontos int
}

type Campeonato struct {
	ordem  []string
	pontos map[string]int
}

func NovoCampeonato(times []string) *Campeonato {
	pontos := make(map[string]int)
	for _, t := range times {
		pontos[t] = 0
	}
	return &Campeonato{ordem: times, pontos: pontos}
}

func (c *Campeonato) registrar_resultado(timeA string, timeB string, golsA int, golsB int) {
	// TODO
}

func (c *Campeonato) ranking() []ResultadoRanking {
	// TODO
	return nil
}
[[ASCEND::RUNNER]]
func main() {
	reader := bufio.NewReader(os.Stdin)
	var nTimes int
	fmt.Fscan(reader, &nTimes)
	reader.ReadString('\n')
	times := make([]string, nTimes)
	for i := 0; i < nTimes; i++ {
		linha, _ := reader.ReadString('\n')
		times[i] = strings.TrimRight(linha, "\r\n")
	}
	campeonato := NovoCampeonato(times)
	var nResultados int
	fmt.Fscan(reader, &nResultados)
	for i := 0; i < nResultados; i++ {
		var a, b string
		var ga, gb int
		fmt.Fscan(reader, &a, &b, &ga, &gb)
		campeonato.registrar_resultado(a, b, ga, gb)
	}
	for _, r := range campeonato.ranking() {
		fmt.Printf("%s:%d\n", r.Time, r.Pontos)
	}
}$GO_32$
)
WHERE slug = 'trilha-n5-classificador-times';

-- trilha-n5-votacao-desempate
UPDATE challenges
SET starter_code_by_language = jsonb_build_object(
  'python', $PY_33$class Votacao:
    def __init__(self, candidatos_em_ordem: list[str]):
        self.ordem_inscricao = candidatos_em_ordem
        self.votos = {c: 0 for c in candidatos_em_ordem}

    def votar(self, candidato: str) -> None:
        pass

    def ranking(self) -> list[tuple[str, int]]:
        pass

[[ASCEND::RUNNER]]
n_candidatos = int(input())
candidatos = [input() for _ in range(n_candidatos)]
votacao = Votacao(candidatos)
n_votos = int(input())
for _ in range(n_votos):
    votacao.votar(input())
for nome, votos in votacao.ranking():
    print(f"{nome}:{votos}")
$PY_33$,
  'javascript', $JS_33$class Votacao {
  constructor(candidatos_em_ordem) {
    this.ordem_inscricao = candidatos_em_ordem;
    this.votos = {};
    for (const c of candidatos_em_ordem) this.votos[c] = 0;
  }

  votar(candidato) {
    // TODO
  }

  ranking() {
    // TODO
  }
}
[[ASCEND::RUNNER]]
const linhas = require('fs').readFileSync(0, 'utf8').split('\n');
let i = 0;
const n_candidatos = parseInt(linhas[i++], 10);
const candidatos = [];
for (let c = 0; c < n_candidatos; c++) candidatos.push(linhas[i++]);
const votacao = new Votacao(candidatos);
const n_votos = parseInt(linhas[i++], 10);
for (let v = 0; v < n_votos; v++) votacao.votar(linhas[i++]);
for (const [nome, votos] of votacao.ranking()) {
  console.log(`${nome}:${votos}`);
}$JS_33$,
  'go', $GO_33$package main

import (
	"bufio"
	"fmt"
	"os"
	"strings"
)

type ResultadoVoto struct {
	Nome  string
	Votos int
}

type Votacao struct {
	ordemInscricao []string
	votos          map[string]int
}

func NovaVotacao(candidatosEmOrdem []string) *Votacao {
	votos := make(map[string]int)
	for _, c := range candidatosEmOrdem {
		votos[c] = 0
	}
	return &Votacao{ordemInscricao: candidatosEmOrdem, votos: votos}
}

func (v *Votacao) votar(candidato string) {
	// TODO
}

func (v *Votacao) ranking() []ResultadoVoto {
	// TODO
	return nil
}
[[ASCEND::RUNNER]]
func main() {
	reader := bufio.NewReader(os.Stdin)
	var nCandidatos int
	fmt.Fscan(reader, &nCandidatos)
	reader.ReadString('\n')
	candidatos := make([]string, nCandidatos)
	for i := 0; i < nCandidatos; i++ {
		linha, _ := reader.ReadString('\n')
		candidatos[i] = strings.TrimRight(linha, "\r\n")
	}
	votacao := NovaVotacao(candidatos)
	var nVotos int
	fmt.Fscan(reader, &nVotos)
	reader.ReadString('\n')
	for i := 0; i < nVotos; i++ {
		linha, _ := reader.ReadString('\n')
		votacao.votar(strings.TrimRight(linha, "\r\n"))
	}
	for _, r := range votacao.ranking() {
		fmt.Printf("%s:%d\n", r.Nome, r.Votos)
	}
}$GO_33$
)
WHERE slug = 'trilha-n5-votacao-desempate';

-- trilha-n5-calculadora-frete
UPDATE challenges
SET starter_code_by_language = jsonb_build_object(
  'python', $PY_34$def calcular_frete(peso: float, distancia: float, tipo: str) -> float:
    pass

[[ASCEND::RUNNER]]
peso = float(input())
distancia = float(input())
tipo = input()
print(f"{calcular_frete(peso, distancia, tipo):.2f}")
$PY_34$,
  'javascript', $JS_34$function calcular_frete(peso, distancia, tipo) {
  // TODO
}
[[ASCEND::RUNNER]]
const __linhas = require('fs').readFileSync(0, 'utf8').split('\n');
const peso = parseFloat(__linhas[0]);
const distancia = parseFloat(__linhas[1]);
const tipo = __linhas[2];
console.log(calcular_frete(peso, distancia, tipo).toFixed(2));$JS_34$,
  'go', $GO_34$package main

import (
	"bufio"
	"fmt"
	"os"
	"strings"
)

func calcular_frete(peso float64, distancia float64, tipo string) float64 {
	// TODO
	return 0
}
[[ASCEND::RUNNER]]
func main() {
	reader := bufio.NewReader(os.Stdin)
	var peso, distancia float64
	fmt.Fscan(reader, &peso)
	fmt.Fscan(reader, &distancia)
	reader.ReadString('\n')
	tipo, _ := reader.ReadString('\n')
	tipo = strings.TrimRight(tipo, "\r\n")
	fmt.Printf("%.2f\n", calcular_frete(peso, distancia, tipo))
}$GO_34$
)
WHERE slug = 'trilha-n5-calculadora-frete';

-- trilha-n5-fila-multiplos-caixas
UPDATE challenges
SET starter_code_by_language = jsonb_build_object(
  'python', $PY_35$class FilaBancoCaixas:
    def __init__(self, n_caixas: int):
        self.n_caixas = n_caixas
        self.espera = []
        self.proximo_caixa = 1

    def chegar(self, nome: str) -> None:
        pass

    def processar(self) -> None:
        pass

[[ASCEND::RUNNER]]
import sys
linhas = sys.stdin.read().split('\n')
n_caixas = int(linhas[0])
fila = FilaBancoCaixas(n_caixas)
for linha in linhas[1:]:
    if not linha.strip():
        continue
    partes = linha.split()
    if partes[0] == "CHEGAR":
        fila.chegar(partes[1])
    elif partes[0] == "PROCESSAR":
        fila.processar()
$PY_35$,
  'javascript', $JS_35$class FilaBancoCaixas {
  constructor(n_caixas) {
    this.n_caixas = n_caixas;
    this.espera = [];
    this.proximo_caixa = 1;
  }

  chegar(nome) {
    // TODO
  }

  processar() {
    // TODO
  }
}
[[ASCEND::RUNNER]]
const linhas = require('fs').readFileSync(0, 'utf8').split('\n');
const n_caixas = parseInt(linhas[0], 10);
const fila = new FilaBancoCaixas(n_caixas);
for (const linha of linhas.slice(1)) {
  if (!linha.trim()) continue;
  const partes = linha.split(/\s+/);
  if (partes[0] === 'CHEGAR') {
    fila.chegar(partes[1]);
  } else if (partes[0] === 'PROCESSAR') {
    fila.processar();
  }
}$JS_35$,
  'go', $GO_35$package main

import (
	"io"
	"os"
	"strconv"
	"strings"
)

type FilaBancoCaixas struct {
	nCaixas      int
	espera       []string
	proximoCaixa int
}

func NovaFilaBancoCaixas(nCaixas int) *FilaBancoCaixas {
	return &FilaBancoCaixas{nCaixas: nCaixas, proximoCaixa: 1}
}

func (f *FilaBancoCaixas) chegar(nome string) {
	// TODO
}

func (f *FilaBancoCaixas) processar() {
	// TODO
}
[[ASCEND::RUNNER]]
func main() {
	data, _ := io.ReadAll(os.Stdin)
	linhas := strings.Split(string(data), "\n")
	nCaixas, _ := strconv.Atoi(linhas[0])
	fila := NovaFilaBancoCaixas(nCaixas)
	for _, linha := range linhas[1:] {
		if strings.TrimSpace(linha) == "" {
			continue
		}
		partes := strings.Fields(linha)
		switch partes[0] {
		case "CHEGAR":
			fila.chegar(partes[1])
		case "PROCESSAR":
			fila.processar()
		}
	}
}$GO_35$
)
WHERE slug = 'trilha-n5-fila-multiplos-caixas';

-- trilha-n6-hash-funcao
UPDATE challenges
SET starter_code_by_language = jsonb_build_object(
  'python', $PY_36$def hash_simples(chave: str, tamanho: int) -> int:
    pass

[[ASCEND::RUNNER]]
chave = input()
tamanho = int(input())
print(hash_simples(chave, tamanho))
$PY_36$,
  'javascript', $JS_36$function hash_simples(chave, tamanho) {
  // TODO
}
[[ASCEND::RUNNER]]
const __linhas = require('fs').readFileSync(0, 'utf8').split('\n');
const chave = __linhas[0];
const tamanho = parseInt(__linhas[1], 10);
console.log(hash_simples(chave, tamanho));$JS_36$,
  'go', $GO_36$package main

import (
	"bufio"
	"fmt"
	"os"
	"strings"
)

func hash_simples(chave string, tamanho int) int {
	// TODO
	return 0
}
[[ASCEND::RUNNER]]
func main() {
	reader := bufio.NewReader(os.Stdin)
	chave, _ := reader.ReadString('\n')
	chave = strings.TrimRight(chave, "\r\n")
	var tamanho int
	fmt.Fscan(reader, &tamanho)
	fmt.Println(hash_simples(chave, tamanho))
}$GO_36$
)
WHERE slug = 'trilha-n6-hash-funcao';

-- trilha-n6-hash-inserir-listar
UPDATE challenges
SET starter_code_by_language = jsonb_build_object(
  'python', $PY_37$class TabelaHash:
    def __init__(self, tamanho: int):
        self.tamanho = tamanho
        self.tabela = [[] for _ in range(tamanho)]

    def _hash(self, chave: str) -> int:
        return sum(ord(c) for c in chave) % self.tamanho

    def inserir(self, chave: str, valor: str) -> None:
        pass

    def listar(self) -> None:
        pass

[[ASCEND::RUNNER]]
import sys
linhas = sys.stdin.read().split('\n')
tamanho = int(linhas[0])
tabela = TabelaHash(tamanho)
for linha in linhas[1:]:
    if not linha.strip():
        continue
    partes = linha.split()
    if partes[0] == "INSERIR":
        tabela.inserir(partes[1], partes[2])
    elif partes[0] == "LISTAR":
        tabela.listar()
$PY_37$,
  'javascript', $JS_37$class TabelaHash {
  constructor(tamanho) {
    this.tamanho = tamanho;
    this.tabela = Array.from({ length: tamanho }, () => []);
  }

  _hash(chave) {
    let soma = 0;
    for (const c of chave) soma += c.codePointAt(0);
    return soma % this.tamanho;
  }

  inserir(chave, valor) {
    // TODO
  }

  listar() {
    // TODO
  }
}
[[ASCEND::RUNNER]]
const linhas = require('fs').readFileSync(0, 'utf8').split('\n');
const tamanho = parseInt(linhas[0], 10);
const tabela = new TabelaHash(tamanho);
for (const linha of linhas.slice(1)) {
  if (!linha.trim()) continue;
  const partes = linha.split(/\s+/);
  if (partes[0] === 'INSERIR') {
    tabela.inserir(partes[1], partes[2]);
  } else if (partes[0] === 'LISTAR') {
    tabela.listar();
  }
}$JS_37$,
  'go', $GO_37$package main

import (
	"io"
	"os"
	"strconv"
	"strings"
)

type TabelaHash struct {
	tamanho int
	tabela  [][]string
}

func NovaTabelaHash(tamanho int) *TabelaHash {
	return &TabelaHash{tamanho: tamanho, tabela: make([][]string, tamanho)}
}

func (t *TabelaHash) _hash(chave string) int {
	soma := 0
	for _, c := range chave {
		soma += int(c)
	}
	return soma % t.tamanho
}

func (t *TabelaHash) inserir(chave string, valor string) {
	// TODO
}

func (t *TabelaHash) listar() {
	// TODO
}
[[ASCEND::RUNNER]]
func main() {
	data, _ := io.ReadAll(os.Stdin)
	linhas := strings.Split(string(data), "\n")
	tamanho, _ := strconv.Atoi(linhas[0])
	tabela := NovaTabelaHash(tamanho)
	for _, linha := range linhas[1:] {
		if strings.TrimSpace(linha) == "" {
			continue
		}
		partes := strings.Fields(linha)
		switch partes[0] {
		case "INSERIR":
			tabela.inserir(partes[1], partes[2])
		case "LISTAR":
			tabela.listar()
		}
	}
}$GO_37$
)
WHERE slug = 'trilha-n6-hash-inserir-listar';

-- trilha-n6-tabela-hash
UPDATE challenges
SET starter_code_by_language = jsonb_build_object(
  'python', $PY_38$class TabelaHash:
    def __init__(self, tamanho: int):
        pass

    def inserir(self, chave: str, valor: str) -> None:
        pass

    def buscar(self, chave: str) -> str | None:
        pass

[[ASCEND::RUNNER]]
import sys
linhas = sys.stdin.read().split('\n')
n = int(linhas[0])
tabela = TabelaHash(n)
for linha in linhas[1:]:
    if not linha.strip():
        continue
    partes = linha.split()
    if partes[0] == "INSERIR":
        tabela.inserir(partes[1], partes[2])
    elif partes[0] == "BUSCAR":
        resultado = tabela.buscar(partes[1])
        print(resultado if resultado is not None else "nao encontrado")
$PY_38$,
  'javascript', $JS_38$class TabelaHash {
  constructor(tamanho) {
    // TODO
  }

  inserir(chave, valor) {
    // TODO
  }

  buscar(chave) {
    // TODO
  }
}
[[ASCEND::RUNNER]]
const linhas = require('fs').readFileSync(0, 'utf8').split('\n');
const n = parseInt(linhas[0], 10);
const tabela = new TabelaHash(n);
for (const linha of linhas.slice(1)) {
  if (!linha.trim()) continue;
  const partes = linha.split(/\s+/);
  if (partes[0] === 'INSERIR') {
    tabela.inserir(partes[1], partes[2]);
  } else if (partes[0] === 'BUSCAR') {
    const resultado = tabela.buscar(partes[1]);
    console.log(resultado !== null && resultado !== undefined ? resultado : 'nao encontrado');
  }
}$JS_38$,
  'go', $GO_38$package main

import (
	"fmt"
	"io"
	"os"
	"strconv"
	"strings"
)

type TabelaHash struct {
	// TODO: adicione os campos necessarios
}

func NovaTabelaHash(tamanho int) *TabelaHash {
	// TODO
	return &TabelaHash{}
}

func (t *TabelaHash) inserir(chave string, valor string) {
	// TODO
}

func (t *TabelaHash) buscar(chave string) (string, bool) {
	// TODO
	return "", false
}
[[ASCEND::RUNNER]]
func main() {
	data, _ := io.ReadAll(os.Stdin)
	linhas := strings.Split(string(data), "\n")
	n, _ := strconv.Atoi(linhas[0])
	tabela := NovaTabelaHash(n)
	for _, linha := range linhas[1:] {
		if strings.TrimSpace(linha) == "" {
			continue
		}
		partes := strings.Fields(linha)
		switch partes[0] {
		case "INSERIR":
			tabela.inserir(partes[1], partes[2])
		case "BUSCAR":
			v, ok := tabela.buscar(partes[1])
			if ok {
				fmt.Println(v)
			} else {
				fmt.Println("nao encontrado")
			}
		}
	}
}$GO_38$
)
WHERE slug = 'trilha-n6-tabela-hash';

-- trilha-n6-hash-remocao
UPDATE challenges
SET starter_code_by_language = jsonb_build_object(
  'python', $PY_39$class TabelaHash:
    def __init__(self, tamanho: int):
        pass

    def inserir(self, chave: str, valor: str) -> None:
        pass

    def remover(self, chave: str) -> None:
        pass

    def buscar(self, chave: str) -> str | None:
        pass

[[ASCEND::RUNNER]]
import sys
linhas = sys.stdin.read().split('\n')
n = int(linhas[0])
tabela = TabelaHash(n)
for linha in linhas[1:]:
    if not linha.strip():
        continue
    partes = linha.split()
    if partes[0] == "INSERIR":
        tabela.inserir(partes[1], partes[2])
    elif partes[0] == "REMOVER":
        tabela.remover(partes[1])
    elif partes[0] == "BUSCAR":
        resultado = tabela.buscar(partes[1])
        print(resultado if resultado is not None else "nao encontrado")
$PY_39$,
  'javascript', $JS_39$class TabelaHash {
  constructor(tamanho) {
    // TODO
  }

  inserir(chave, valor) {
    // TODO
  }

  remover(chave) {
    // TODO
  }

  buscar(chave) {
    // TODO
  }
}
[[ASCEND::RUNNER]]
const linhas = require('fs').readFileSync(0, 'utf8').split('\n');
const n = parseInt(linhas[0], 10);
const tabela = new TabelaHash(n);
for (const linha of linhas.slice(1)) {
  if (!linha.trim()) continue;
  const partes = linha.split(/\s+/);
  if (partes[0] === 'INSERIR') {
    tabela.inserir(partes[1], partes[2]);
  } else if (partes[0] === 'REMOVER') {
    tabela.remover(partes[1]);
  } else if (partes[0] === 'BUSCAR') {
    const resultado = tabela.buscar(partes[1]);
    console.log(resultado !== null && resultado !== undefined ? resultado : 'nao encontrado');
  }
}$JS_39$,
  'go', $GO_39$package main

import (
	"fmt"
	"io"
	"os"
	"strconv"
	"strings"
)

type TabelaHash struct {
	// TODO: adicione os campos necessarios
}

func NovaTabelaHash(tamanho int) *TabelaHash {
	// TODO
	return &TabelaHash{}
}

func (t *TabelaHash) inserir(chave string, valor string) {
	// TODO
}

func (t *TabelaHash) remover(chave string) {
	// TODO
}

func (t *TabelaHash) buscar(chave string) (string, bool) {
	// TODO
	return "", false
}
[[ASCEND::RUNNER]]
func main() {
	data, _ := io.ReadAll(os.Stdin)
	linhas := strings.Split(string(data), "\n")
	n, _ := strconv.Atoi(linhas[0])
	tabela := NovaTabelaHash(n)
	for _, linha := range linhas[1:] {
		if strings.TrimSpace(linha) == "" {
			continue
		}
		partes := strings.Fields(linha)
		switch partes[0] {
		case "INSERIR":
			tabela.inserir(partes[1], partes[2])
		case "REMOVER":
			tabela.remover(partes[1])
		case "BUSCAR":
			v, ok := tabela.buscar(partes[1])
			if ok {
				fmt.Println(v)
			} else {
				fmt.Println("nao encontrado")
			}
		}
	}
}$GO_39$
)
WHERE slug = 'trilha-n6-hash-remocao';

-- trilha-n6-hash-atualizacao
UPDATE challenges
SET starter_code_by_language = jsonb_build_object(
  'python', $PY_40$class TabelaHash:
    def __init__(self, tamanho: int):
        pass

    def inserir(self, chave: str, valor: str) -> None:
        pass

    def buscar(self, chave: str) -> str | None:
        pass

[[ASCEND::RUNNER]]
import sys
linhas = sys.stdin.read().split('\n')
n = int(linhas[0])
tabela = TabelaHash(n)
for linha in linhas[1:]:
    if not linha.strip():
        continue
    partes = linha.split()
    if partes[0] == "INSERIR":
        tabela.inserir(partes[1], partes[2])
    elif partes[0] == "BUSCAR":
        resultado = tabela.buscar(partes[1])
        print(resultado if resultado is not None else "nao encontrado")
$PY_40$,
  'javascript', $JS_40$class TabelaHash {
  constructor(tamanho) {
    // TODO
  }

  inserir(chave, valor) {
    // TODO
  }

  buscar(chave) {
    // TODO
  }
}
[[ASCEND::RUNNER]]
const linhas = require('fs').readFileSync(0, 'utf8').split('\n');
const n = parseInt(linhas[0], 10);
const tabela = new TabelaHash(n);
for (const linha of linhas.slice(1)) {
  if (!linha.trim()) continue;
  const partes = linha.split(/\s+/);
  if (partes[0] === 'INSERIR') {
    tabela.inserir(partes[1], partes[2]);
  } else if (partes[0] === 'BUSCAR') {
    const resultado = tabela.buscar(partes[1]);
    console.log(resultado !== null && resultado !== undefined ? resultado : 'nao encontrado');
  }
}$JS_40$,
  'go', $GO_40$package main

import (
	"fmt"
	"io"
	"os"
	"strconv"
	"strings"
)

type TabelaHash struct {
	// TODO: adicione os campos necessarios
}

func NovaTabelaHash(tamanho int) *TabelaHash {
	// TODO
	return &TabelaHash{}
}

func (t *TabelaHash) inserir(chave string, valor string) {
	// TODO
}

func (t *TabelaHash) buscar(chave string) (string, bool) {
	// TODO
	return "", false
}
[[ASCEND::RUNNER]]
func main() {
	data, _ := io.ReadAll(os.Stdin)
	linhas := strings.Split(string(data), "\n")
	n, _ := strconv.Atoi(linhas[0])
	tabela := NovaTabelaHash(n)
	for _, linha := range linhas[1:] {
		if strings.TrimSpace(linha) == "" {
			continue
		}
		partes := strings.Fields(linha)
		switch partes[0] {
		case "INSERIR":
			tabela.inserir(partes[1], partes[2])
		case "BUSCAR":
			v, ok := tabela.buscar(partes[1])
			if ok {
				fmt.Println(v)
			} else {
				fmt.Println("nao encontrado")
			}
		}
	}
}$GO_40$
)
WHERE slug = 'trilha-n6-hash-atualizacao';

-- trilha-n6-hash-rehashing
UPDATE challenges
SET starter_code_by_language = jsonb_build_object(
  'python', $PY_41$class TabelaHash:
    def __init__(self, tamanho: int):
        pass

    def inserir(self, chave: str, valor: str) -> None:
        pass

    def buscar(self, chave: str) -> str | None:
        pass

[[ASCEND::RUNNER]]
import sys
linhas = sys.stdin.read().split('\n')
n = int(linhas[0])
tabela = TabelaHash(n)
for linha in linhas[1:]:
    if not linha.strip():
        continue
    partes = linha.split()
    if partes[0] == "INSERIR":
        tabela.inserir(partes[1], partes[2])
    elif partes[0] == "TAMANHO":
        print(tabela.tamanho)
    elif partes[0] == "BUSCAR":
        resultado = tabela.buscar(partes[1])
        print(resultado if resultado is not None else "nao encontrado")
$PY_41$,
  'javascript', $JS_41$class TabelaHash {
  constructor(tamanho) {
    // TODO
  }

  inserir(chave, valor) {
    // TODO
  }

  buscar(chave) {
    // TODO
  }
}
[[ASCEND::RUNNER]]
const linhas = require('fs').readFileSync(0, 'utf8').split('\n');
const n = parseInt(linhas[0], 10);
const tabela = new TabelaHash(n);
for (const linha of linhas.slice(1)) {
  if (!linha.trim()) continue;
  const partes = linha.split(/\s+/);
  if (partes[0] === 'INSERIR') {
    tabela.inserir(partes[1], partes[2]);
  } else if (partes[0] === 'TAMANHO') {
    console.log(tabela.tamanho);
  } else if (partes[0] === 'BUSCAR') {
    const resultado = tabela.buscar(partes[1]);
    console.log(resultado !== null && resultado !== undefined ? resultado : 'nao encontrado');
  }
}$JS_41$,
  'go', $GO_41$package main

import (
	"fmt"
	"io"
	"os"
	"strconv"
	"strings"
)

type TabelaHash struct {
	tamanho int
	// TODO: adicione os demais campos necessarios
}

func NovaTabelaHash(tamanho int) *TabelaHash {
	// TODO
	return &TabelaHash{}
}

func (t *TabelaHash) inserir(chave string, valor string) {
	// TODO
}

func (t *TabelaHash) buscar(chave string) (string, bool) {
	// TODO
	return "", false
}
[[ASCEND::RUNNER]]
func main() {
	data, _ := io.ReadAll(os.Stdin)
	linhas := strings.Split(string(data), "\n")
	n, _ := strconv.Atoi(linhas[0])
	tabela := NovaTabelaHash(n)
	for _, linha := range linhas[1:] {
		if strings.TrimSpace(linha) == "" {
			continue
		}
		partes := strings.Fields(linha)
		switch partes[0] {
		case "INSERIR":
			tabela.inserir(partes[1], partes[2])
		case "TAMANHO":
			fmt.Println(tabela.tamanho)
		case "BUSCAR":
			v, ok := tabela.buscar(partes[1])
			if ok {
				fmt.Println(v)
			} else {
				fmt.Println("nao encontrado")
			}
		}
	}
}$GO_41$
)
WHERE slug = 'trilha-n6-hash-rehashing';

UPDATE challenges SET language = NULL WHERE slug LIKE 'trilha-%';

COMMIT;
