import { useEffect, useState, type FormEvent } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { createLiveSession, finishLiveSession, getLiveDashboard, getLiveSession, joinLiveSession, listLiveSessions, listProblemLists, type LiveDashboard, type LiveSession, type LiveSessionDetail, type ProblemList } from '../api'
import { useAuth } from '../auth/useAuth'

const POLL_MS = 2000
function statusText(s: string) { return s === 'waiting' ? 'Aguardando participantes' : s === 'active' ? 'Em andamento' : 'Encerrada' }

export function LiveSessionsPage() {
 const { id } = useParams<{id:string}>(); const navigate=useNavigate(); const { isTeacher, user }=useAuth(); const [sessions,setSessions]=useState<LiveSession[]>([]); const [lists,setLists]=useState<ProblemList[]>([]); const [listID,setListID]=useState(''); const [minimum,setMinimum]=useState(3); const [detail,setDetail]=useState<LiveSessionDetail|null>(null); const [dashboard,setDashboard]=useState<LiveDashboard|null>(null); const [error,setError]=useState<string|null>(null)
 useEffect(()=>{let alive=true; const load=async()=>{try{if(id){const d=await getLiveSession(id);if(alive)setDetail(d);if(isTeacher){const x=await getLiveDashboard(id);if(alive)setDashboard(x)}}else{const x=await listLiveSessions();if(alive)setSessions(x);if(isTeacher){const l=(await listProblemLists()).filter(item=>item.teacher_id===user?.id);if(alive){setLists(l);if(!listID)setListID(l[0]?.id??'')}}}}catch(e){if(alive)setError(e instanceof Error?e.message:'Falha ao carregar sessões')}};void load();const t=setInterval(()=>void load(),POLL_MS);return()=>{alive=false;clearInterval(t)}},[id,isTeacher,listID,user?.id])
 async function create(e:FormEvent){e.preventDefault();try{const x=await createLiveSession(listID,minimum);navigate(`/sessoes/${x.id}`)}catch(e){setError(e instanceof Error?e.message:'Falha ao criar sessão')}}
 async function join(){if(!id)return;try{await joinLiveSession(id);setDetail(await getLiveSession(id))}catch(e){setError(e instanceof Error?e.message:'Falha ao entrar')}}
 async function finish(){if(!id||!confirm('Encerrar esta sessão?'))return;try{await finishLiveSession(id);setDetail(await getLiveSession(id));setDashboard(null)}catch(e){setError(e instanceof Error?e.message:'Falha ao encerrar')}}
 if(!id)return <main className="page-shell"><section className="hero"><p className="eyebrow">Atividade em grupo</p><h1>sessões ao vivo</h1><p className="muted">Entre em uma atividade ou conduza sua turma.</p></section>{error&&<p className="status-message status-error">{error}</p>}{isTeacher&&<section className="panel submission-panel"><div className="submission-panel__body"><h2>Nova sessão</h2><form onSubmit={create}><label>Lista<select value={listID} onChange={e=>setListID(e.target.value)} required>{lists.map(l=><option key={l.id} value={l.id}>{l.title}</option>)}</select></label><label>Mínimo de participantes<input type="number" min="1" value={minimum} onChange={e=>setMinimum(Number(e.target.value))}/></label><button className="challenge-submit" disabled={!listID}>criar sessão</button></form></div></section>}<section className="history-section"><h2 className="section-title">Disponíveis</h2>{sessions.map(s=><article className="list-item" key={s.id}><div className="list-item__head"><div><strong>{s.title}</strong><p className="muted">Professor: {s.teacher_email} · {statusText(s.status)} · {s.participant_count}/{s.min_participants}</p></div><Link className="challenge-submit" to={`/sessoes/${s.id}`}>{isTeacher&&s.created_by===undefined?'abrir':'abrir'}</Link></div></article>)}{sessions.length===0&&<p className="muted">Nenhuma sessão aberta.</p>}</section></main>
 if(!detail)return <main className="page-shell"><p>Carregando sessão...</p></main>; const s=detail.session
 return <main className="page-shell"><Link className="back-link" to="/sessoes">← sessões ao vivo</Link><section className="hero"><p className="eyebrow">Live session</p><h1>{s.title}</h1><p className="muted">{statusText(s.status)} · {detail.participants.length}/{s.min_participants} participantes</p>{s.status==='waiting'&&!isTeacher&&!s.joined?<button className="challenge-submit" onClick={()=>void join()}>entrar</button>:null}{isTeacher&&s.status!=='finished'?<button className="btn-secondary" onClick={()=>void finish()}>encerrar sessão</button>:null}</section>{error&&<p className="status-message status-error">{error}</p>}<section className="panel submission-panel"><div className="submission-panel__body"><h2>{s.status==='waiting'?'Lobby':'Desafios'}</h2>{s.status==='waiting'?<><p className="muted">A atividade começará automaticamente quando atingir o mínimo.</p><ul>{detail.participants.map(p=><li key={p.user_id}>{p.email}</li>)}</ul></>:<div className="list-items">{s.items.map((item,i)=><article className="list-item" key={item.id}><div className="list-item__head"><span>{i+1}. {item.title}</span><Link className="challenge-submit" to={`/challenges/${item.linked_challenge_id}?liveSessionId=${s.id}`}>resolver</Link></div></article>)}</div>}</div></section>{isTeacher&&dashboard?<Dashboard dashboard={dashboard}/>:null}</main>
}
function Dashboard({dashboard}:{dashboard:LiveDashboard}){const items=dashboard.session.items;return <section className="history-section"><h2 className="section-title">Acompanhamento ao vivo</h2><div className="table-wrap"><table><thead><tr><th>Aluno</th><th>Total</th><th>Aceitos</th>{items.map((i,n)=><th key={i.id}>C{n+1}</th>)}</tr></thead><tbody>{dashboard.students.map(st=><tr key={st.user_id}><td>{st.email}</td><td>{st.attempts}</td><td>{st.accepted}</td>{items.map(i=>{const c=st.challenges[i.linked_challenge_id??''];return <td key={i.id}>{!c?'—':c.accepted?`✓ (${c.attempts})`:`✗ (${c.attempts})`}</td>})}</tr>)}</tbody></table></div><p className="muted">Por desafio: {items.map((i,n)=>`C${n+1}: ${dashboard.challenge_accepted[i.linked_challenge_id??'']??0} aceitos / ${dashboard.challenge_attempts[i.linked_challenge_id??'']??0} tentativas`).join(' · ')}</p></section>}
